<?xml version="1.0" encoding="utf-8"?>
<Database Name="VehixFoundation" Class="VehixFoundationDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=qa-sql-01\a;Initial Catalog=VehixFoundation;Integrated Security=True" SettingsObjectName="Vehix.QA.WebTest.Data.Properties.Settings" SettingsPropertyName="VehixFoundationConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="Branding.AccountExecInfoTable" Member="AccountExecInfoTables">
    <Type Name="AccountExecInfoTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_CreatorID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_UpdaterID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DeletorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AccountExec" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Market" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="Branding.TollFreeProductTable" Member="TollFreeProductTables">
    <Type Name="TollFreeProductTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NoScrub" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="ForwardingPhone" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="Branding.AutoSalesManagerInfoTable" Member="AutoSalesManagerInfoTables">
    <Type Name="AutoSalesManagerInfoTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_CreatorID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_UpdaterID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DeletorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SalesManager" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Market" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="Branding.BrandInfoTable" Member="BrandInfoTables">
    <Type Name="BrandInfoTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_CreatorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_UpdaterID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DeletorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Brand" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="BrandInfoTable_SellerInfoBrandInfoTable" Member="SellerInfoBrandInfoTables" ThisKey="ID" OtherKey="BrandInfo" Type="SellerInfoBrandInfoTable" />
    </Type>
  </Table>
  <Table Name="Branding.CableExecInfoTable" Member="CableExecInfoTables">
    <Type Name="CableExecInfoTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_CreatorID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_UpdaterID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DeletorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CableExec" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Market" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="Branding.DealerGroupInfoTable" Member="DealerGroupInfoTables">
    <Type Name="DealerGroupInfoTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_CreatorID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_UpdaterID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DeletorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DealerGroup" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="BeginDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ContactInfo" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="DealerGroupInfoTable_DealerGroupProductTable" Member="DealerGroupProductTables" ThisKey="ID" OtherKey="DealerGroup" Type="DealerGroupProductTable" />
    </Type>
  </Table>
  <Table Name="Branding.DealerGroupProductTable" Member="DealerGroupProductTables">
    <Type Name="DealerGroupProductTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_CreatorID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_UpdaterID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DeletorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DealerGroup" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="BeginDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="DealerGroupProductTable_DealerGroupShowcaseAdProductTable" Member="DealerGroupShowcaseAdProductTables" ThisKey="ID" OtherKey="ID" Type="DealerGroupShowcaseAdProductTable" />
      <Association Name="DealerGroupProductTable_DealerGroupVideoProductTable" Member="DealerGroupVideoProductTables" ThisKey="ID" OtherKey="ID" Type="DealerGroupVideoProductTable" />
      <Association Name="DealerGroupInfoTable_DealerGroupProductTable" Member="DealerGroupInfoTable" ThisKey="DealerGroup" OtherKey="ID" Type="DealerGroupInfoTable" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="Branding.DealerGroupShowcaseAdMakeLocaleTable" Member="DealerGroupShowcaseAdMakeLocaleTables">
    <Type Name="DealerGroupShowcaseAdMakeLocaleTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_CreatorID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_UpdaterID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DeletorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DealerGroupShowcaseAd" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Locale" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Make" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Conditions" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="DealerGroupShowcaseAdProductTable_DealerGroupShowcaseAdMakeLocaleTable" Member="DealerGroupShowcaseAdProductTable" ThisKey="DealerGroupShowcaseAd" OtherKey="ID" Type="DealerGroupShowcaseAdProductTable" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="Branding.DealerGroupShowcaseAdProductTable" Member="DealerGroupShowcaseAdProductTables">
    <Type Name="DealerGroupShowcaseAdProductTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="LogoFile" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TagLine" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="DealerGroupShowcaseAdProductTable_DealerGroupShowcaseAdMakeLocaleTable" Member="DealerGroupShowcaseAdMakeLocaleTables" ThisKey="ID" OtherKey="DealerGroupShowcaseAd" Type="DealerGroupShowcaseAdMakeLocaleTable" />
      <Association Name="DealerGroupProductTable_DealerGroupShowcaseAdProductTable" Member="DealerGroupProductTable" ThisKey="ID" OtherKey="ID" Type="DealerGroupProductTable" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="Branding.DealerGroupVideoProductTable" Member="DealerGroupVideoProductTables">
    <Type Name="DealerGroupVideoProductTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Uri" Type="System.String" DbType="NVarChar(2048) NOT NULL" CanBeNull="false" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="DealerGroupProductTable_DealerGroupVideoProductTable" Member="DealerGroupProductTable" ThisKey="ID" OtherKey="ID" Type="DealerGroupProductTable" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="Branding.DealerSignUpTable" Member="DealerSignUpTables">
    <Type Name="DealerSignUpTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_CreatorID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_UpdaterID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DeletorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(19) NOT NULL" CanBeNull="false" />
      <Column Name="DealerName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Street" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="SubmitDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HomeNetOrderID" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="FormData" Type="System.Xml.Linq.XElement" DbType="Xml" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="Branding.FranchiseNumberIdentityTable" Member="FranchiseNumberIdentityTables">
    <Type Name="FranchiseNumberIdentityTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_CreatorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_UpdaterID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DeletorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Value" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="Branding.HostedWebsiteProductTable" Member="HostedWebsiteProductTables">
    <Type Name="HostedWebsiteProductTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Website" Type="System.String" DbType="NVarChar(512) NOT NULL" CanBeNull="false" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="Branding.ListingProductTable" Member="ListingProductTables">
    <Type Name="ListingProductTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="IsPremier" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="Branding.PackageProductTable" Member="PackageProductTables">
    <Type Name="PackageProductTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="PackageName" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="PackageProductTypeTable_PackageProductTable" Member="PackageProductTypeTable" ThisKey="PackageName" OtherKey="Name" Type="PackageProductTypeTable" IsForeignKey="true" />
      <Association Name="SellerInfoProductTable_PackageProductTable" Member="SellerInfoProductTable" ThisKey="ID" OtherKey="ID" Type="SellerInfoProductTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Branding.PackageProductTypeTable" Member="PackageProductTypeTables">
    <Type Name="PackageProductTypeTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_CreatorID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_UpdaterID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DeletorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(40) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="PackageProductTypeTable_PackageProductTable" Member="PackageProductTables" ThisKey="Name" OtherKey="PackageName" Type="PackageProductTable" />
    </Type>
  </Table>
  <Table Name="Branding.PagerConnectProductTable" Member="PagerConnectProductTables">
    <Type Name="PagerConnectProductTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Mailbox" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="Branding.PersonLocaleTable" Member="PersonLocaleTables">
    <Type Name="PersonLocaleTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_CreatorID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_UpdaterID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DeletorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Person" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Locale" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AssociationType" Type="System.String" DbType="NVarChar(16) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="Branding.PositionInfoTable" Member="PositionInfoTables">
    <Type Name="PositionInfoTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_CreatorID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_UpdaterID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DeletorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Person" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Locale" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="SecurityRole" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="Branding.PrivateListingProductTable" Member="PrivateListingProductTables">
    <Type Name="PrivateListingProductTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="DisplayPhoneNumber" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="OptIn" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="Package" Type="System.String" DbType="NVarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="Branding.SellerInfoAggregateDataTable" Member="SellerInfoAggregateDataTables">
    <Type Name="SellerInfoAggregateDataTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_CreatorID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_UpdaterID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DeletorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SellerInfo" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Street" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="PostalCode" Type="System.String" DbType="NVarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="Latitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Longitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="PriorityName" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="TollFreeNumber" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="LogoUrl" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="VideoUrl" Type="System.String" DbType="NVarChar(2048)" CanBeNull="true" />
      <Column Name="WebsiteUrl" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HasUsedInventory" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="HasNewInventory" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Association Name="SellerInfoTable_SellerInfoAggregateDataTable" Member="SellerInfoTable" ThisKey="SellerInfo" OtherKey="ID" Type="SellerInfoTable" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="Branding.SellerInfoBrandInfoTable" Member="SellerInfoBrandInfoTables">
    <Type Name="SellerInfoBrandInfoTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_CreatorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_UpdaterID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DeletorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SellerInfo" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="BrandInfo" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="BrandInfoTable_SellerInfoBrandInfoTable" Member="BrandInfoTable" ThisKey="BrandInfo" OtherKey="ID" Type="BrandInfoTable" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="SellerInfoTable_SellerInfoBrandInfoTable" Member="SellerInfoTable" ThisKey="SellerInfo" OtherKey="ID" Type="SellerInfoTable" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="Branding.SellerInfoContactInfoTable" Member="SellerInfoContactInfoTables">
    <Type Name="SellerInfoContactInfoTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_CreatorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_UpdaterID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DeletorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SellerInfo" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ContactInfo" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="SellerInfoTable_SellerInfoContactInfoTable" Member="SellerInfoTable" ThisKey="SellerInfo" OtherKey="ID" Type="SellerInfoTable" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="Branding.SellerInfoMakeTable" Member="SellerInfoMakeTables">
    <Type Name="SellerInfoMakeTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_CreatorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_UpdaterID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DeletorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SellerInfo" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Make" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Licensed" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="Condition" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="SellerInfoTable_SellerInfoMakeTable" Member="SellerInfoTable" ThisKey="SellerInfo" OtherKey="ID" Type="SellerInfoTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Branding.SellerInfoMediaTable" Member="SellerInfoMediaTables">
    <Type Name="SellerInfoMediaTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_CreatorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_UpdaterID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DeletorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SellerInfo" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[File]" Member="File" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="SellerInfoTable_SellerInfoMediaTable" Member="SellerInfoTable" ThisKey="SellerInfo" OtherKey="ID" Type="SellerInfoTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Branding.SellerInfoProductTable" Member="SellerInfoProductTables">
    <Type Name="SellerInfoProductTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_CreatorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_UpdaterID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DeletorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SellerInfo" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="BeginDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="SellerInfoProductTable_PackageProductTable" Member="PackageProductTables" ThisKey="ID" OtherKey="ID" Type="PackageProductTable" />
      <Association Name="SellerInfoProductTable_SellerShowcaseAdProductTable" Member="SellerShowcaseAdProductTables" ThisKey="ID" OtherKey="ID" Type="SellerShowcaseAdProductTable" />
      <Association Name="SellerInfoTable_SellerInfoProductTable" Member="SellerInfoTable" ThisKey="SellerInfo" OtherKey="ID" Type="SellerInfoTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Branding.SellerInfoTable" Member="SellerInfoTables">
    <Type Name="SellerInfoTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_CreatorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_UpdaterID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DeletorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Seller" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SellerInfoType" Type="System.String" DbType="NVarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="BeginDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ContactInfo" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="FranchiseNumber" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="PolkCode" Type="System.String" DbType="NVarChar(35)" CanBeNull="true" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="InventoryManagementType" Type="System.String" DbType="NVarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="Market" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="MonthEndBookQuantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HomenetToken" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="NoScrub" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="AllowLiquidusVOD" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="LogoVisible" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="DirectionsVisible" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Association Name="SellerInfoTable_SellerInfoAggregateDataTable" Member="SellerInfoAggregateDataTables" ThisKey="ID" OtherKey="SellerInfo" Type="SellerInfoAggregateDataTable" />
      <Association Name="SellerInfoTable_SellerInfoBrandInfoTable" Member="SellerInfoBrandInfoTables" ThisKey="ID" OtherKey="SellerInfo" Type="SellerInfoBrandInfoTable" />
      <Association Name="SellerInfoTable_SellerInfoContactInfoTable" Member="SellerInfoContactInfoTables" ThisKey="ID" OtherKey="SellerInfo" Type="SellerInfoContactInfoTable" />
      <Association Name="SellerInfoTable_SellerInfoMakeTable" Member="SellerInfoMakeTables" ThisKey="ID" OtherKey="SellerInfo" Type="SellerInfoMakeTable" />
      <Association Name="SellerInfoTable_SellerInfoMediaTable" Member="SellerInfoMediaTables" ThisKey="ID" OtherKey="SellerInfo" Type="SellerInfoMediaTable" />
      <Association Name="SellerInfoTable_SellerInfoProductTable" Member="SellerInfoProductTables" ThisKey="ID" OtherKey="SellerInfo" Type="SellerInfoProductTable" />
    </Type>
  </Table>
  <Table Name="Branding.SellerShowcaseAdProductTable" Member="SellerShowcaseAdProductTables">
    <Type Name="SellerShowcaseAdProductTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="MakeID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Conditions" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Locale" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="SellerInfoProductTable_SellerShowcaseAdProductTable" Member="SellerInfoProductTable" ThisKey="ID" OtherKey="ID" Type="SellerInfoProductTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Branding.SellerVideoProductTable" Member="SellerVideoProductTables">
    <Type Name="SellerVideoProductTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Uri" Type="System.String" DbType="NVarChar(2048) NOT NULL" CanBeNull="false" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="Branding.SyndicateGroupTable" Member="SyndicateGroupTables">
    <Type Name="SyndicateGroupTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_CreatorID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_UpdaterID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DeletorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(40) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="SyndicateGroupTable_SyndicateTable" Member="SyndicateTables" ThisKey="Name" OtherKey="PartnerGroupName" Type="SyndicateTable" />
    </Type>
  </Table>
  <Table Name="Branding.SyndicateTable" Member="SyndicateTables">
    <Type Name="SyndicateTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_CreatorID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_UpdaterID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DeletorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PartnerGroupName" Type="System.String" DbType="NVarChar(40) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IbsKey" Type="System.String" DbType="NVarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SiteUrl" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="CallLetters" Type="System.String" DbType="NVarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LogoUrl" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="SyndicateGroupTable_SyndicateTable" Member="SyndicateGroupTable" ThisKey="PartnerGroupName" OtherKey="Name" Type="SyndicateGroupTable" IsForeignKey="true" />
    </Type>
  </Table>
</Database>