<?xml version="1.0" encoding="utf-8"?>
<Database Name="VehixFoundation" Class="VehixFoundationInventoryDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=qa-sql-01\a;Initial Catalog=VehixFoundation;Integrated Security=True" SettingsObjectName="Nathandelane.WatiN.VehixTesting.Data.Properties.Settings" SettingsPropertyName="VehixFoundationConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="Inventory.AftermarketFeatureTable" Member="AftermarketFeatureTables">
    <Type Name="AftermarketFeatureTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_CreatorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_UpdaterID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DeletorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FeatureType" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="AftermarketFeatureTable_InventoryVehicleAftermarketFeatureTable" Member="InventoryVehicleAftermarketFeatureTables" ThisKey="ID" OtherKey="AftermarketFeature" Type="InventoryVehicleAftermarketFeatureTable" />
      <Association Name="AftermarketFeatureTypeTable_AftermarketFeatureTable" Member="AftermarketFeatureTypeTable" ThisKey="FeatureType" OtherKey="Name" Type="AftermarketFeatureTypeTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Inventory.SellerPriorityLevelTable" Member="SellerPriorityLevelTables">
    <Type Name="SellerPriorityLevelTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_CreatorID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_UpdaterID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DeletorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Catalog" Type="System.String" DbType="NVarChar(40) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(40) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PriorityLevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DefaultNumberOfImagesVisible" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DefaultResearchMediaVisible" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Association Name="SellerPriorityLevelTable_InventorySellerInfoTable" Member="InventorySellerInfoTables" ThisKey="Catalog,Name,PriorityLevel" OtherKey="Catalog,PriorityName,PriorityLevel" Type="InventorySellerInfoTable" />
      <Association Name="InventoryCatalogTable_SellerPriorityLevelTable" Member="InventoryCatalogTable" ThisKey="Catalog" OtherKey="Name" Type="InventoryCatalogTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Inventory.AftermarketFeatureTypeTable" Member="AftermarketFeatureTypeTables">
    <Type Name="AftermarketFeatureTypeTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_CreatorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_UpdaterID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DeletorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(64) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="AftermarketFeatureTypeTable_AftermarketFeatureTable" Member="AftermarketFeatureTables" ThisKey="Name" OtherKey="FeatureType" Type="AftermarketFeatureTable" />
    </Type>
  </Table>
  <Table Name="Inventory.Background_JobStatus" Member="Background_JobStatus">
    <Type Name="Background_JobStatus">
      <Column Name="job_id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="timestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="message" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="Inventory.ConditionExtendedBodyStyleMakeModelTrimAggregateTable" Member="ConditionExtendedBodyStyleMakeModelTrimAggregateTables">
    <Type Name="ConditionExtendedBodyStyleMakeModelTrimAggregateTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_CreatorID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_UpdaterID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DeletorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Condition" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExtendedBodyStyle" Type="System.String" DbType="NVarChar(90)" CanBeNull="true" />
      <Column Name="Make" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Trim" Type="System.String" DbType="NVarChar(90)" CanBeNull="true" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="Inventory.InventoryCatalogTable" Member="InventoryCatalogTables">
    <Type Name="InventoryCatalogTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_CreatorID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_UpdaterID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DeletorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(40) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="InventoryCatalogTable_SellerPriorityLevelTable" Member="SellerPriorityLevelTables" ThisKey="Name" OtherKey="Catalog" Type="SellerPriorityLevelTable" />
      <Association Name="InventoryCatalogTable_ListingPriorityLevelTable" Member="ListingPriorityLevelTables" ThisKey="Name" OtherKey="Catalog" Type="ListingPriorityLevelTable" />
    </Type>
  </Table>
  <Table Name="Inventory.InventoryLocationTable" Member="InventoryLocationTables">
    <Type Name="InventoryLocationTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_CreatorID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_UpdaterID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DeletorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Seller" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PostalCode" Type="System.String" DbType="NVarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Latitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Longitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="Inventory.InventorySellerInfoTable" Member="InventorySellerInfoTables">
    <Type Name="InventorySellerInfoTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_CreatorID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_UpdaterID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DeletorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Seller" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StandardMessage" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Disclaimer" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="HideNewStockImages" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="HideUsedStockImages" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="HideNewPrices" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="HideUsedPrices" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="NewPriceAdjustment" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UsedPriceAdjustment" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ShowUsedInventory" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="ShowNewInventory" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Catalog" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="PriorityName" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="PriorityLevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NewInventoryOriginationSource" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="UsedInventoryOriginationSource" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="ShowInventoryExplanation" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="PartnerInventoryFeeds" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Association Name="InventorySellerInfoTable_InventoryVehicleTable" Member="InventoryVehicleTables" ThisKey="ID" OtherKey="InventorySellerInfo" Type="InventoryVehicleTable" />
      <Association Name="SellerPriorityLevelTable_InventorySellerInfoTable" Member="SellerPriorityLevelTable" ThisKey="Catalog,PriorityName,PriorityLevel" OtherKey="Catalog,Name,PriorityLevel" Type="SellerPriorityLevelTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Inventory.InventoryVehicleAftermarketFeatureTable" Member="InventoryVehicleAftermarketFeatureTables">
    <Type Name="InventoryVehicleAftermarketFeatureTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_CreatorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_UpdaterID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DeletorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="InventoryVehicle" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="AftermarketFeature" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="AftermarketFeatureTable_InventoryVehicleAftermarketFeatureTable" Member="AftermarketFeatureTable" ThisKey="AftermarketFeature" OtherKey="ID" Type="AftermarketFeatureTable" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="InventoryVehicleTable_InventoryVehicleAftermarketFeatureTable" Member="InventoryVehicleTable" ThisKey="InventoryVehicle" OtherKey="ID" Type="InventoryVehicleTable" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="Inventory.InventoryVehicleExtendedBodyStyleTable" Member="InventoryVehicleExtendedBodyStyleTables">
    <Type Name="InventoryVehicleExtendedBodyStyleTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_CreatorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_UpdaterID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DeletorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SellerInfo" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="InventoryVehicle" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="IsPrimary" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="InventoryVehicleTable_InventoryVehicleExtendedBodyStyleTable" Member="InventoryVehicleTable" ThisKey="InventoryVehicle" OtherKey="ID" Type="InventoryVehicleTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Inventory.InventoryVehicleFileTable" Member="InventoryVehicleFileTables">
    <Type Name="InventoryVehicleFileTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_CreatorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_UpdaterID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DeletorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SellerInfo" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="InventoryVehicle" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="MediaFile" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Sequence" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RecreateThumbnail" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Association Name="InventoryVehicleTable_InventoryVehicleFileTable" Member="InventoryVehicleTable" ThisKey="InventoryVehicle" OtherKey="ID" Type="InventoryVehicleTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Inventory.InventoryVehicleFileTableTemp" Member="InventoryVehicleFileTableTemps">
    <Type Name="InventoryVehicleFileTableTemp">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_CreatorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_UpdaterID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DeletorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SellerInfo" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="InventoryVehicle" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="MediaFile" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Sequence" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="Inventory.InventoryVehicleOptionalFeatureTable" Member="InventoryVehicleOptionalFeatureTables">
    <Type Name="InventoryVehicleOptionalFeatureTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_CreatorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_UpdaterID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DeletorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="InventoryVehicle" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="OptionalFeature" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="InventoryVehicleTable_InventoryVehicleOptionalFeatureTable" Member="InventoryVehicleTable" ThisKey="InventoryVehicle" OtherKey="ID" Type="InventoryVehicleTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Inventory.InventoryVehiclePhotoProductTable" Member="InventoryVehiclePhotoProductTables">
    <Type Name="InventoryVehiclePhotoProductTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="MaximumNumberOfPhotos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="Inventory.InventoryVehicleTable" Member="InventoryVehicleTables">
    <Type Name="InventoryVehicleTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_CreatorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_UpdaterID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DeletorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SellerInfo" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="SellerInfoProduct" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="InventorySellerInfo" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="SoldDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ExpirationDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="HiddenByVehix" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="HiddenByVehixReason" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DealerCustomChanges" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HiddenByDealer" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Vin" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="IsVinValid" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="ResearchTrimID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ResearchManufacturerID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ResearchManufacturer" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ResearchMakeID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ResearchMake" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ResearchModelID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ResearchModel" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ResearchShortModel" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ResearchYear" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ResearchModelConfidence" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ResearchFullTrimName" Type="System.String" DbType="NVarChar(90) NOT NULL" CanBeNull="false" />
      <Column Name="ResearchStyleName" Type="System.String" DbType="NVarChar(55) NOT NULL" CanBeNull="false" />
      <Column Name="ResearchTrimName" Type="System.String" DbType="NVarChar(55) NOT NULL" CanBeNull="false" />
      <Column Name="LegacyBodyCode" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="LegacyVehixDealerID" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ExternalVehicleID" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Condition" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DealerMake" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DealerModel" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DealerShortModel" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DealerYear" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DealerFullTrimName" Type="System.String" DbType="NVarChar(90)" CanBeNull="true" />
      <Column Name="DealerStyleName" Type="System.String" DbType="NVarChar(55)" CanBeNull="true" />
      <Column Name="DealerTrimName" Type="System.String" DbType="NVarChar(55)" CanBeNull="true" />
      <Column Name="DealerStockNumber" Type="System.String" DbType="NVarChar(35)" CanBeNull="true" />
      <Column Name="DealerModelNumber" Type="System.String" DbType="NVarChar(35)" CanBeNull="true" />
      <Column Name="DealerBodyStyle" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DealerNumberOfDoors" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="DealerGenericExteriorColor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DealerDetailedExteriorColor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DealerGenericInteriorColor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DealerDetailedInteriorColor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DealerMileage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DealerTransmissionDescr" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DealerTransmissionType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DealerSpeeds" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DealerDisplacement" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DealerLiters" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="DealerCubicInches" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DealerEngine" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DealerCylinders" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DealerFuelType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DealerDriveTrain" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DealerMPGCity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DealerMPGHwy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DealerIsVehicleCertified" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="DealerSellingPrice" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="DealerMarketClassName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Msrp" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="BookValue" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="InvoicePrice" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="NadaPrice" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="DealerHasInternetSpecialPrice" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="DealerInternetSpecialPrice" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="DealerInternetSpecialStartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DealerInternetSpecialEndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DealerInternetSpecialPayment" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="DealerInternetSpecialDisclaimer" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="DealerDateInStock" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DealerShortComment" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="DealerShortDescription" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="DealerLongDescription" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="DealerGenericStandardEquipment" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="DealerGenericOptionalEquipment" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="IsCommercial" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="IsFleet" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="Latitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Longitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="PreferredImageName" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="PreferredImageUrl" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="NumberOfImages" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="EtlOptions" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DealerPassengerCapacity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PreferredImageManagementType" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="IsPreferredImageVerified" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="PreferredImageLastVerification" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="StockImageName" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="StockImageUrl" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Catalog" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="SellerPriorityName" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="SellerPriorityLevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ListingPriorityName" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="ListingPriorityLevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quarantine" Type="System.String" DbType="NVarChar(28) NOT NULL" CanBeNull="false" />
      <Column Name="CarfaxOffering" Type="System.Char" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="ListingNumberOfImagesVisible" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ListingResearchMediaVisible" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Association Name="InventoryVehicleTable_InventoryVehicleAftermarketFeatureTable" Member="InventoryVehicleAftermarketFeatureTables" ThisKey="ID" OtherKey="InventoryVehicle" Type="InventoryVehicleAftermarketFeatureTable" />
      <Association Name="InventoryVehicleTable_InventoryVehicleExtendedBodyStyleTable" Member="InventoryVehicleExtendedBodyStyleTables" ThisKey="ID" OtherKey="InventoryVehicle" Type="InventoryVehicleExtendedBodyStyleTable" />
      <Association Name="InventoryVehicleTable_InventoryVehicleFileTable" Member="InventoryVehicleFileTables" ThisKey="ID" OtherKey="InventoryVehicle" Type="InventoryVehicleFileTable" />
      <Association Name="InventoryVehicleTable_InventoryVehicleOptionalFeatureTable" Member="InventoryVehicleOptionalFeatureTables" ThisKey="ID" OtherKey="InventoryVehicle" Type="InventoryVehicleOptionalFeatureTable" />
      <Association Name="InventoryVehicleTable_InventoryVehicleTrimTable" Member="InventoryVehicleTrimTables" ThisKey="ID" OtherKey="InventoryVehicle" Type="InventoryVehicleTrimTable" />
      <Association Name="InventorySellerInfoTable_InventoryVehicleTable" Member="InventorySellerInfoTable" ThisKey="InventorySellerInfo" OtherKey="ID" Type="InventorySellerInfoTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Inventory.InventoryVehicleTableTemp" Member="InventoryVehicleTableTemps">
    <Type Name="InventoryVehicleTableTemp">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_CreatorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_UpdaterID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DeletorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SellerInfo" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="SellerInfoProduct" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="InventorySellerInfo" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="SoldDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ExpirationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HiddenByVehix" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="HiddenByVehixReason" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DealerCustomChanges" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HiddenByDealer" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Vin" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="IsVinValid" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="ResearchTrimID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ResearchManufacturerID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ResearchManufacturer" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ResearchMakeID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ResearchMake" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ResearchModelID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ResearchModel" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ResearchShortModel" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ResearchYear" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ResearchModelConfidence" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ResearchFullTrimName" Type="System.String" DbType="NVarChar(90) NOT NULL" CanBeNull="false" />
      <Column Name="ResearchStyleName" Type="System.String" DbType="NVarChar(55) NOT NULL" CanBeNull="false" />
      <Column Name="ResearchTrimName" Type="System.String" DbType="NVarChar(55) NOT NULL" CanBeNull="false" />
      <Column Name="LegacyBodyCode" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="LegacyVehixDealerID" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ExternalVehicleID" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Condition" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DealerMake" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DealerModel" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DealerShortModel" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DealerYear" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DealerFullTrimName" Type="System.String" DbType="NVarChar(90)" CanBeNull="true" />
      <Column Name="DealerStyleName" Type="System.String" DbType="NVarChar(55)" CanBeNull="true" />
      <Column Name="DealerTrimName" Type="System.String" DbType="NVarChar(55)" CanBeNull="true" />
      <Column Name="DealerStockNumber" Type="System.String" DbType="NVarChar(35)" CanBeNull="true" />
      <Column Name="DealerModelNumber" Type="System.String" DbType="NVarChar(35)" CanBeNull="true" />
      <Column Name="DealerBodyStyle" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DealerNumberOfDoors" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="DealerGenericExteriorColor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DealerDetailedExteriorColor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DealerGenericInteriorColor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DealerDetailedInteriorColor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DealerMileage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DealerTransmissionDescr" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DealerTransmissionType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DealerSpeeds" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DealerDisplacement" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DealerLiters" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="DealerCubicInches" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DealerEngine" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DealerCylinders" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DealerFuelType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DealerDriveTrain" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DealerMPGCity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DealerMPGHwy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DealerIsVehicleCertified" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="DealerSellingPrice" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="DealerMarketClassName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Msrp" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="BookValue" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="InvoicePrice" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="NadaPrice" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="DealerHasInternetSpecialPrice" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="DealerInternetSpecialPrice" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="DealerInternetSpecialStartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DealerInternetSpecialEndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DealerInternetSpecialPayment" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="DealerInternetSpecialDisclaimer" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="DealerDateInStock" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DealerShortComment" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="DealerShortDescription" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="DealerLongDescription" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="DealerGenericStandardEquipment" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="DealerGenericOptionalEquipment" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="IsCommercial" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="IsFleet" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="Latitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Longitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="PreferredImageName" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="PreferredImageUrl" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="IsPreferredImageFromInventory" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="NumberOfImages" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="EtlOptions" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DealerPassengerCapacity" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="Inventory.InventoryVehicleTrimTable" Member="InventoryVehicleTrimTables">
    <Type Name="InventoryVehicleTrimTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_CreatorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_UpdaterID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DeletorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SellerInfo" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="InventoryVehicle" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Trim" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="InventoryVehicleTable_InventoryVehicleTrimTable" Member="InventoryVehicleTable" ThisKey="InventoryVehicle" OtherKey="ID" Type="InventoryVehicleTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Inventory.ListingPriorityLevelTable" Member="ListingPriorityLevelTables">
    <Type Name="ListingPriorityLevelTable">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_CreatorID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_UpdaterID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DeletorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="VFX_DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VFX_DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Catalog" Type="System.String" DbType="NVarChar(40) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(40) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="PriorityLevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ETL_NaturalKey" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ETL_Hash" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ETL_JobCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETL_DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="InventoryCatalogTable_ListingPriorityLevelTable" Member="InventoryCatalogTable" ThisKey="Catalog" OtherKey="Name" Type="InventoryCatalogTable" IsForeignKey="true" />
    </Type>
  </Table>
</Database>