#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nathandelane.WatiN.VehixTesting.Data.VehixFoundation
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="VehixFoundation")]
	public partial class VehixFoundationInventoryImportDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public VehixFoundationInventoryImportDataContext() : 
				base(global::Vehix.QA.WebTest.Data.Properties.Settings.Default.VehixFoundationConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public VehixFoundationInventoryImportDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VehixFoundationInventoryImportDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VehixFoundationInventoryImportDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VehixFoundationInventoryImportDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<FileColumnTable> FileColumnTables
		{
			get
			{
				return this.GetTable<FileColumnTable>();
			}
		}
		
		public System.Data.Linq.Table<InventorySystemTable> InventorySystemTables
		{
			get
			{
				return this.GetTable<InventorySystemTable>();
			}
		}
		
		public System.Data.Linq.Table<ImportRuleTable> ImportRuleTables
		{
			get
			{
				return this.GetTable<ImportRuleTable>();
			}
		}
		
		public System.Data.Linq.Table<InventoryAccountTable> InventoryAccountTables
		{
			get
			{
				return this.GetTable<InventoryAccountTable>();
			}
		}
		
		public System.Data.Linq.Table<InventorySourceTable> InventorySourceTables
		{
			get
			{
				return this.GetTable<InventorySourceTable>();
			}
		}
	}
	
	[Table(Name="InventoryImport.FileColumnTable")]
	public partial class FileColumnTable
	{
		
		private long _ID;
		
		private System.Nullable<long> _VFX_CreatorID;
		
		private System.Nullable<long> _VFX_UpdaterID;
		
		private System.Nullable<long> _VFX_DeletorID;
		
		private System.DateTime _VFX_DateCreated;
		
		private System.DateTime _VFX_DateUpdated;
		
		private System.Nullable<System.DateTime> _VFX_DateDeleted;
		
		private System.Nullable<int> _CreateDateColumn;
		
		private System.Nullable<int> _UpdateDateColumn;
		
		private System.Nullable<int> _VinColumn;
		
		private System.Nullable<int> _AccountColumn;
		
		private System.Nullable<int> _StockNumberColumn;
		
		private System.Nullable<int> _MileageColumn;
		
		private System.Nullable<int> _NewPriceColumn;
		
		private System.Nullable<int> _UsedPriceColumn;
		
		private System.Nullable<int> _YearColumn;
		
		private System.Nullable<int> _MakeColumn;
		
		private System.Nullable<int> _ModelColumn;
		
		private System.Nullable<int> _TrimColumn;
		
		private System.Nullable<int> _NewUsedColumn;
		
		private System.Nullable<int> _CPOColumn;
		
		private System.Nullable<int> _ColorColumn;
		
		private System.Nullable<int> _ColorCodeColumn;
		
		private System.Nullable<int> _InteriorColorColumn;
		
		private System.Nullable<int> _ImageCodeColumn;
		
		private System.Nullable<int> _Comment1Column;
		
		private System.Nullable<int> _Comment2Column;
		
		private System.Nullable<int> _Comment3Column;
		
		private System.Nullable<int> _Comment4Column;
		
		private System.Nullable<int> _Comment5Column;
		
		private System.Nullable<int> _StockDateColumn;
		
		private System.Nullable<int> _EngineColumn;
		
		private System.Nullable<int> _InductionColumn;
		
		private System.Nullable<int> _TransmissionColumn;
		
		private System.Nullable<int> _EngineSizeColumn;
		
		private System.Nullable<int> _CylindersColumn;
		
		private System.Nullable<int> _InvoiceColumn;
		
		private System.Nullable<int> _WarrantyColumn;
		
		private System.Nullable<int> _LimitedWarrantyColumn;
		
		private System.Nullable<int> _ServiceAgreementColumn;
		
		private System.Nullable<int> _ManufacturerCodeColumn;
		
		private System.Nullable<int> _FuelTypeColumn;
		
		private System.Nullable<int> _MilesPerGallonColumn;
		
		private System.Nullable<int> _CabStyleColumn;
		
		private System.Nullable<int> _BedStyleColumn;
		
		private System.Nullable<int> _OtherColumn1;
		
		private string _OtherTitle1;
		
		private System.Nullable<int> _OtherColumn2;
		
		private string _OtherTitle2;
		
		private System.Nullable<int> _OtherColumn3;
		
		private string _OtherTitle3;
		
		private System.Nullable<int> _OtherColumn4;
		
		private string _OtherTitle4;
		
		private string _ETL_NaturalKey;
		
		private System.Data.Linq.Binary _ETL_Hash;
		
		private string _ETL_JobCategory;
		
		private System.Nullable<System.DateTime> _ETL_DateEffective;
		
		private System.Nullable<int> _ImageUrlColumn;
		
		public FileColumnTable()
		{
		}
		
		[Column(Storage="_ID", DbType="BigInt NOT NULL")]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[Column(Storage="_VFX_CreatorID", DbType="BigInt")]
		public System.Nullable<long> VFX_CreatorID
		{
			get
			{
				return this._VFX_CreatorID;
			}
			set
			{
				if ((this._VFX_CreatorID != value))
				{
					this._VFX_CreatorID = value;
				}
			}
		}
		
		[Column(Storage="_VFX_UpdaterID", DbType="BigInt")]
		public System.Nullable<long> VFX_UpdaterID
		{
			get
			{
				return this._VFX_UpdaterID;
			}
			set
			{
				if ((this._VFX_UpdaterID != value))
				{
					this._VFX_UpdaterID = value;
				}
			}
		}
		
		[Column(Storage="_VFX_DeletorID", DbType="BigInt")]
		public System.Nullable<long> VFX_DeletorID
		{
			get
			{
				return this._VFX_DeletorID;
			}
			set
			{
				if ((this._VFX_DeletorID != value))
				{
					this._VFX_DeletorID = value;
				}
			}
		}
		
		[Column(Storage="_VFX_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime VFX_DateCreated
		{
			get
			{
				return this._VFX_DateCreated;
			}
			set
			{
				if ((this._VFX_DateCreated != value))
				{
					this._VFX_DateCreated = value;
				}
			}
		}
		
		[Column(Storage="_VFX_DateUpdated", DbType="DateTime NOT NULL")]
		public System.DateTime VFX_DateUpdated
		{
			get
			{
				return this._VFX_DateUpdated;
			}
			set
			{
				if ((this._VFX_DateUpdated != value))
				{
					this._VFX_DateUpdated = value;
				}
			}
		}
		
		[Column(Storage="_VFX_DateDeleted", DbType="DateTime")]
		public System.Nullable<System.DateTime> VFX_DateDeleted
		{
			get
			{
				return this._VFX_DateDeleted;
			}
			set
			{
				if ((this._VFX_DateDeleted != value))
				{
					this._VFX_DateDeleted = value;
				}
			}
		}
		
		[Column(Storage="_CreateDateColumn", DbType="Int")]
		public System.Nullable<int> CreateDateColumn
		{
			get
			{
				return this._CreateDateColumn;
			}
			set
			{
				if ((this._CreateDateColumn != value))
				{
					this._CreateDateColumn = value;
				}
			}
		}
		
		[Column(Storage="_UpdateDateColumn", DbType="Int")]
		public System.Nullable<int> UpdateDateColumn
		{
			get
			{
				return this._UpdateDateColumn;
			}
			set
			{
				if ((this._UpdateDateColumn != value))
				{
					this._UpdateDateColumn = value;
				}
			}
		}
		
		[Column(Storage="_VinColumn", DbType="Int")]
		public System.Nullable<int> VinColumn
		{
			get
			{
				return this._VinColumn;
			}
			set
			{
				if ((this._VinColumn != value))
				{
					this._VinColumn = value;
				}
			}
		}
		
		[Column(Storage="_AccountColumn", DbType="Int")]
		public System.Nullable<int> AccountColumn
		{
			get
			{
				return this._AccountColumn;
			}
			set
			{
				if ((this._AccountColumn != value))
				{
					this._AccountColumn = value;
				}
			}
		}
		
		[Column(Storage="_StockNumberColumn", DbType="Int")]
		public System.Nullable<int> StockNumberColumn
		{
			get
			{
				return this._StockNumberColumn;
			}
			set
			{
				if ((this._StockNumberColumn != value))
				{
					this._StockNumberColumn = value;
				}
			}
		}
		
		[Column(Storage="_MileageColumn", DbType="Int")]
		public System.Nullable<int> MileageColumn
		{
			get
			{
				return this._MileageColumn;
			}
			set
			{
				if ((this._MileageColumn != value))
				{
					this._MileageColumn = value;
				}
			}
		}
		
		[Column(Storage="_NewPriceColumn", DbType="Int")]
		public System.Nullable<int> NewPriceColumn
		{
			get
			{
				return this._NewPriceColumn;
			}
			set
			{
				if ((this._NewPriceColumn != value))
				{
					this._NewPriceColumn = value;
				}
			}
		}
		
		[Column(Storage="_UsedPriceColumn", DbType="Int")]
		public System.Nullable<int> UsedPriceColumn
		{
			get
			{
				return this._UsedPriceColumn;
			}
			set
			{
				if ((this._UsedPriceColumn != value))
				{
					this._UsedPriceColumn = value;
				}
			}
		}
		
		[Column(Storage="_YearColumn", DbType="Int")]
		public System.Nullable<int> YearColumn
		{
			get
			{
				return this._YearColumn;
			}
			set
			{
				if ((this._YearColumn != value))
				{
					this._YearColumn = value;
				}
			}
		}
		
		[Column(Storage="_MakeColumn", DbType="Int")]
		public System.Nullable<int> MakeColumn
		{
			get
			{
				return this._MakeColumn;
			}
			set
			{
				if ((this._MakeColumn != value))
				{
					this._MakeColumn = value;
				}
			}
		}
		
		[Column(Storage="_ModelColumn", DbType="Int")]
		public System.Nullable<int> ModelColumn
		{
			get
			{
				return this._ModelColumn;
			}
			set
			{
				if ((this._ModelColumn != value))
				{
					this._ModelColumn = value;
				}
			}
		}
		
		[Column(Storage="_TrimColumn", DbType="Int")]
		public System.Nullable<int> TrimColumn
		{
			get
			{
				return this._TrimColumn;
			}
			set
			{
				if ((this._TrimColumn != value))
				{
					this._TrimColumn = value;
				}
			}
		}
		
		[Column(Storage="_NewUsedColumn", DbType="Int")]
		public System.Nullable<int> NewUsedColumn
		{
			get
			{
				return this._NewUsedColumn;
			}
			set
			{
				if ((this._NewUsedColumn != value))
				{
					this._NewUsedColumn = value;
				}
			}
		}
		
		[Column(Storage="_CPOColumn", DbType="Int")]
		public System.Nullable<int> CPOColumn
		{
			get
			{
				return this._CPOColumn;
			}
			set
			{
				if ((this._CPOColumn != value))
				{
					this._CPOColumn = value;
				}
			}
		}
		
		[Column(Storage="_ColorColumn", DbType="Int")]
		public System.Nullable<int> ColorColumn
		{
			get
			{
				return this._ColorColumn;
			}
			set
			{
				if ((this._ColorColumn != value))
				{
					this._ColorColumn = value;
				}
			}
		}
		
		[Column(Storage="_ColorCodeColumn", DbType="Int")]
		public System.Nullable<int> ColorCodeColumn
		{
			get
			{
				return this._ColorCodeColumn;
			}
			set
			{
				if ((this._ColorCodeColumn != value))
				{
					this._ColorCodeColumn = value;
				}
			}
		}
		
		[Column(Storage="_InteriorColorColumn", DbType="Int")]
		public System.Nullable<int> InteriorColorColumn
		{
			get
			{
				return this._InteriorColorColumn;
			}
			set
			{
				if ((this._InteriorColorColumn != value))
				{
					this._InteriorColorColumn = value;
				}
			}
		}
		
		[Column(Storage="_ImageCodeColumn", DbType="Int")]
		public System.Nullable<int> ImageCodeColumn
		{
			get
			{
				return this._ImageCodeColumn;
			}
			set
			{
				if ((this._ImageCodeColumn != value))
				{
					this._ImageCodeColumn = value;
				}
			}
		}
		
		[Column(Storage="_Comment1Column", DbType="Int")]
		public System.Nullable<int> Comment1Column
		{
			get
			{
				return this._Comment1Column;
			}
			set
			{
				if ((this._Comment1Column != value))
				{
					this._Comment1Column = value;
				}
			}
		}
		
		[Column(Storage="_Comment2Column", DbType="Int")]
		public System.Nullable<int> Comment2Column
		{
			get
			{
				return this._Comment2Column;
			}
			set
			{
				if ((this._Comment2Column != value))
				{
					this._Comment2Column = value;
				}
			}
		}
		
		[Column(Storage="_Comment3Column", DbType="Int")]
		public System.Nullable<int> Comment3Column
		{
			get
			{
				return this._Comment3Column;
			}
			set
			{
				if ((this._Comment3Column != value))
				{
					this._Comment3Column = value;
				}
			}
		}
		
		[Column(Storage="_Comment4Column", DbType="Int")]
		public System.Nullable<int> Comment4Column
		{
			get
			{
				return this._Comment4Column;
			}
			set
			{
				if ((this._Comment4Column != value))
				{
					this._Comment4Column = value;
				}
			}
		}
		
		[Column(Storage="_Comment5Column", DbType="Int")]
		public System.Nullable<int> Comment5Column
		{
			get
			{
				return this._Comment5Column;
			}
			set
			{
				if ((this._Comment5Column != value))
				{
					this._Comment5Column = value;
				}
			}
		}
		
		[Column(Storage="_StockDateColumn", DbType="Int")]
		public System.Nullable<int> StockDateColumn
		{
			get
			{
				return this._StockDateColumn;
			}
			set
			{
				if ((this._StockDateColumn != value))
				{
					this._StockDateColumn = value;
				}
			}
		}
		
		[Column(Storage="_EngineColumn", DbType="Int")]
		public System.Nullable<int> EngineColumn
		{
			get
			{
				return this._EngineColumn;
			}
			set
			{
				if ((this._EngineColumn != value))
				{
					this._EngineColumn = value;
				}
			}
		}
		
		[Column(Storage="_InductionColumn", DbType="Int")]
		public System.Nullable<int> InductionColumn
		{
			get
			{
				return this._InductionColumn;
			}
			set
			{
				if ((this._InductionColumn != value))
				{
					this._InductionColumn = value;
				}
			}
		}
		
		[Column(Storage="_TransmissionColumn", DbType="Int")]
		public System.Nullable<int> TransmissionColumn
		{
			get
			{
				return this._TransmissionColumn;
			}
			set
			{
				if ((this._TransmissionColumn != value))
				{
					this._TransmissionColumn = value;
				}
			}
		}
		
		[Column(Storage="_EngineSizeColumn", DbType="Int")]
		public System.Nullable<int> EngineSizeColumn
		{
			get
			{
				return this._EngineSizeColumn;
			}
			set
			{
				if ((this._EngineSizeColumn != value))
				{
					this._EngineSizeColumn = value;
				}
			}
		}
		
		[Column(Storage="_CylindersColumn", DbType="Int")]
		public System.Nullable<int> CylindersColumn
		{
			get
			{
				return this._CylindersColumn;
			}
			set
			{
				if ((this._CylindersColumn != value))
				{
					this._CylindersColumn = value;
				}
			}
		}
		
		[Column(Storage="_InvoiceColumn", DbType="Int")]
		public System.Nullable<int> InvoiceColumn
		{
			get
			{
				return this._InvoiceColumn;
			}
			set
			{
				if ((this._InvoiceColumn != value))
				{
					this._InvoiceColumn = value;
				}
			}
		}
		
		[Column(Storage="_WarrantyColumn", DbType="Int")]
		public System.Nullable<int> WarrantyColumn
		{
			get
			{
				return this._WarrantyColumn;
			}
			set
			{
				if ((this._WarrantyColumn != value))
				{
					this._WarrantyColumn = value;
				}
			}
		}
		
		[Column(Storage="_LimitedWarrantyColumn", DbType="Int")]
		public System.Nullable<int> LimitedWarrantyColumn
		{
			get
			{
				return this._LimitedWarrantyColumn;
			}
			set
			{
				if ((this._LimitedWarrantyColumn != value))
				{
					this._LimitedWarrantyColumn = value;
				}
			}
		}
		
		[Column(Storage="_ServiceAgreementColumn", DbType="Int")]
		public System.Nullable<int> ServiceAgreementColumn
		{
			get
			{
				return this._ServiceAgreementColumn;
			}
			set
			{
				if ((this._ServiceAgreementColumn != value))
				{
					this._ServiceAgreementColumn = value;
				}
			}
		}
		
		[Column(Storage="_ManufacturerCodeColumn", DbType="Int")]
		public System.Nullable<int> ManufacturerCodeColumn
		{
			get
			{
				return this._ManufacturerCodeColumn;
			}
			set
			{
				if ((this._ManufacturerCodeColumn != value))
				{
					this._ManufacturerCodeColumn = value;
				}
			}
		}
		
		[Column(Storage="_FuelTypeColumn", DbType="Int")]
		public System.Nullable<int> FuelTypeColumn
		{
			get
			{
				return this._FuelTypeColumn;
			}
			set
			{
				if ((this._FuelTypeColumn != value))
				{
					this._FuelTypeColumn = value;
				}
			}
		}
		
		[Column(Storage="_MilesPerGallonColumn", DbType="Int")]
		public System.Nullable<int> MilesPerGallonColumn
		{
			get
			{
				return this._MilesPerGallonColumn;
			}
			set
			{
				if ((this._MilesPerGallonColumn != value))
				{
					this._MilesPerGallonColumn = value;
				}
			}
		}
		
		[Column(Storage="_CabStyleColumn", DbType="Int")]
		public System.Nullable<int> CabStyleColumn
		{
			get
			{
				return this._CabStyleColumn;
			}
			set
			{
				if ((this._CabStyleColumn != value))
				{
					this._CabStyleColumn = value;
				}
			}
		}
		
		[Column(Storage="_BedStyleColumn", DbType="Int")]
		public System.Nullable<int> BedStyleColumn
		{
			get
			{
				return this._BedStyleColumn;
			}
			set
			{
				if ((this._BedStyleColumn != value))
				{
					this._BedStyleColumn = value;
				}
			}
		}
		
		[Column(Storage="_OtherColumn1", DbType="Int")]
		public System.Nullable<int> OtherColumn1
		{
			get
			{
				return this._OtherColumn1;
			}
			set
			{
				if ((this._OtherColumn1 != value))
				{
					this._OtherColumn1 = value;
				}
			}
		}
		
		[Column(Storage="_OtherTitle1", DbType="NVarChar(30)")]
		public string OtherTitle1
		{
			get
			{
				return this._OtherTitle1;
			}
			set
			{
				if ((this._OtherTitle1 != value))
				{
					this._OtherTitle1 = value;
				}
			}
		}
		
		[Column(Storage="_OtherColumn2", DbType="Int")]
		public System.Nullable<int> OtherColumn2
		{
			get
			{
				return this._OtherColumn2;
			}
			set
			{
				if ((this._OtherColumn2 != value))
				{
					this._OtherColumn2 = value;
				}
			}
		}
		
		[Column(Storage="_OtherTitle2", DbType="NVarChar(30)")]
		public string OtherTitle2
		{
			get
			{
				return this._OtherTitle2;
			}
			set
			{
				if ((this._OtherTitle2 != value))
				{
					this._OtherTitle2 = value;
				}
			}
		}
		
		[Column(Storage="_OtherColumn3", DbType="Int")]
		public System.Nullable<int> OtherColumn3
		{
			get
			{
				return this._OtherColumn3;
			}
			set
			{
				if ((this._OtherColumn3 != value))
				{
					this._OtherColumn3 = value;
				}
			}
		}
		
		[Column(Storage="_OtherTitle3", DbType="NVarChar(30)")]
		public string OtherTitle3
		{
			get
			{
				return this._OtherTitle3;
			}
			set
			{
				if ((this._OtherTitle3 != value))
				{
					this._OtherTitle3 = value;
				}
			}
		}
		
		[Column(Storage="_OtherColumn4", DbType="Int")]
		public System.Nullable<int> OtherColumn4
		{
			get
			{
				return this._OtherColumn4;
			}
			set
			{
				if ((this._OtherColumn4 != value))
				{
					this._OtherColumn4 = value;
				}
			}
		}
		
		[Column(Storage="_OtherTitle4", DbType="NVarChar(30)")]
		public string OtherTitle4
		{
			get
			{
				return this._OtherTitle4;
			}
			set
			{
				if ((this._OtherTitle4 != value))
				{
					this._OtherTitle4 = value;
				}
			}
		}
		
		[Column(Storage="_ETL_NaturalKey", DbType="VarChar(256)")]
		public string ETL_NaturalKey
		{
			get
			{
				return this._ETL_NaturalKey;
			}
			set
			{
				if ((this._ETL_NaturalKey != value))
				{
					this._ETL_NaturalKey = value;
				}
			}
		}
		
		[Column(Storage="_ETL_Hash", DbType="Binary(16)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ETL_Hash
		{
			get
			{
				return this._ETL_Hash;
			}
			set
			{
				if ((this._ETL_Hash != value))
				{
					this._ETL_Hash = value;
				}
			}
		}
		
		[Column(Storage="_ETL_JobCategory", DbType="VarChar(50)")]
		public string ETL_JobCategory
		{
			get
			{
				return this._ETL_JobCategory;
			}
			set
			{
				if ((this._ETL_JobCategory != value))
				{
					this._ETL_JobCategory = value;
				}
			}
		}
		
		[Column(Storage="_ETL_DateEffective", DbType="DateTime")]
		public System.Nullable<System.DateTime> ETL_DateEffective
		{
			get
			{
				return this._ETL_DateEffective;
			}
			set
			{
				if ((this._ETL_DateEffective != value))
				{
					this._ETL_DateEffective = value;
				}
			}
		}
		
		[Column(Storage="_ImageUrlColumn", DbType="Int")]
		public System.Nullable<int> ImageUrlColumn
		{
			get
			{
				return this._ImageUrlColumn;
			}
			set
			{
				if ((this._ImageUrlColumn != value))
				{
					this._ImageUrlColumn = value;
				}
			}
		}
	}
	
	[Table(Name="InventoryImport.InventorySystemTable")]
	public partial class InventorySystemTable
	{
		
		private long _ID;
		
		private System.Nullable<long> _VFX_CreatorID;
		
		private System.Nullable<long> _VFX_UpdaterID;
		
		private System.Nullable<long> _VFX_DeletorID;
		
		private System.DateTime _VFX_DateCreated;
		
		private System.DateTime _VFX_DateUpdated;
		
		private System.Nullable<System.DateTime> _VFX_DateDeleted;
		
		private string _Name;
		
		private string _ETL_NaturalKey;
		
		private System.Data.Linq.Binary _ETL_Hash;
		
		private string _ETL_JobCategory;
		
		private System.Nullable<System.DateTime> _ETL_DateEffective;
		
		public InventorySystemTable()
		{
		}
		
		[Column(Storage="_ID", DbType="BigInt NOT NULL")]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[Column(Storage="_VFX_CreatorID", DbType="BigInt")]
		public System.Nullable<long> VFX_CreatorID
		{
			get
			{
				return this._VFX_CreatorID;
			}
			set
			{
				if ((this._VFX_CreatorID != value))
				{
					this._VFX_CreatorID = value;
				}
			}
		}
		
		[Column(Storage="_VFX_UpdaterID", DbType="BigInt")]
		public System.Nullable<long> VFX_UpdaterID
		{
			get
			{
				return this._VFX_UpdaterID;
			}
			set
			{
				if ((this._VFX_UpdaterID != value))
				{
					this._VFX_UpdaterID = value;
				}
			}
		}
		
		[Column(Storage="_VFX_DeletorID", DbType="BigInt")]
		public System.Nullable<long> VFX_DeletorID
		{
			get
			{
				return this._VFX_DeletorID;
			}
			set
			{
				if ((this._VFX_DeletorID != value))
				{
					this._VFX_DeletorID = value;
				}
			}
		}
		
		[Column(Storage="_VFX_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime VFX_DateCreated
		{
			get
			{
				return this._VFX_DateCreated;
			}
			set
			{
				if ((this._VFX_DateCreated != value))
				{
					this._VFX_DateCreated = value;
				}
			}
		}
		
		[Column(Storage="_VFX_DateUpdated", DbType="DateTime NOT NULL")]
		public System.DateTime VFX_DateUpdated
		{
			get
			{
				return this._VFX_DateUpdated;
			}
			set
			{
				if ((this._VFX_DateUpdated != value))
				{
					this._VFX_DateUpdated = value;
				}
			}
		}
		
		[Column(Storage="_VFX_DateDeleted", DbType="DateTime")]
		public System.Nullable<System.DateTime> VFX_DateDeleted
		{
			get
			{
				return this._VFX_DateDeleted;
			}
			set
			{
				if ((this._VFX_DateDeleted != value))
				{
					this._VFX_DateDeleted = value;
				}
			}
		}
		
		[Column(Storage="_Name", DbType="NVarChar(32) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[Column(Storage="_ETL_NaturalKey", DbType="VarChar(256)")]
		public string ETL_NaturalKey
		{
			get
			{
				return this._ETL_NaturalKey;
			}
			set
			{
				if ((this._ETL_NaturalKey != value))
				{
					this._ETL_NaturalKey = value;
				}
			}
		}
		
		[Column(Storage="_ETL_Hash", DbType="Binary(16)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ETL_Hash
		{
			get
			{
				return this._ETL_Hash;
			}
			set
			{
				if ((this._ETL_Hash != value))
				{
					this._ETL_Hash = value;
				}
			}
		}
		
		[Column(Storage="_ETL_JobCategory", DbType="VarChar(50)")]
		public string ETL_JobCategory
		{
			get
			{
				return this._ETL_JobCategory;
			}
			set
			{
				if ((this._ETL_JobCategory != value))
				{
					this._ETL_JobCategory = value;
				}
			}
		}
		
		[Column(Storage="_ETL_DateEffective", DbType="DateTime")]
		public System.Nullable<System.DateTime> ETL_DateEffective
		{
			get
			{
				return this._ETL_DateEffective;
			}
			set
			{
				if ((this._ETL_DateEffective != value))
				{
					this._ETL_DateEffective = value;
				}
			}
		}
	}
	
	[Table(Name="InventoryImport.ImportRuleTable")]
	public partial class ImportRuleTable
	{
		
		private long _ID;
		
		private long _VFX_CreatorID;
		
		private long _VFX_UpdaterID;
		
		private System.Nullable<long> _VFX_DeletorID;
		
		private System.DateTime _VFX_DateCreated;
		
		private System.DateTime _VFX_DateUpdated;
		
		private System.Nullable<System.DateTime> _VFX_DateDeleted;
		
		private System.Nullable<long> _InventorySource;
		
		private string _CheckFieldName;
		
		private string _CheckFieldValue;
		
		private string _SetFieldName;
		
		private string _SetFieldValue;
		
		private string _SetFieldDefault;
		
		private string _CaseSensitive;
		
		private string _NoMatchAction;
		
		private System.Nullable<int> _Sequence;
		
		private string _Status;
		
		private string _Comments;
		
		private string _ETL_NaturalKey;
		
		private System.Data.Linq.Binary _ETL_Hash;
		
		private string _ETL_JobCategory;
		
		private System.Nullable<System.DateTime> _ETL_DateEffective;
		
		public ImportRuleTable()
		{
		}
		
		[Column(Storage="_ID", DbType="BigInt NOT NULL")]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[Column(Storage="_VFX_CreatorID", DbType="BigInt NOT NULL")]
		public long VFX_CreatorID
		{
			get
			{
				return this._VFX_CreatorID;
			}
			set
			{
				if ((this._VFX_CreatorID != value))
				{
					this._VFX_CreatorID = value;
				}
			}
		}
		
		[Column(Storage="_VFX_UpdaterID", DbType="BigInt NOT NULL")]
		public long VFX_UpdaterID
		{
			get
			{
				return this._VFX_UpdaterID;
			}
			set
			{
				if ((this._VFX_UpdaterID != value))
				{
					this._VFX_UpdaterID = value;
				}
			}
		}
		
		[Column(Storage="_VFX_DeletorID", DbType="BigInt")]
		public System.Nullable<long> VFX_DeletorID
		{
			get
			{
				return this._VFX_DeletorID;
			}
			set
			{
				if ((this._VFX_DeletorID != value))
				{
					this._VFX_DeletorID = value;
				}
			}
		}
		
		[Column(Storage="_VFX_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime VFX_DateCreated
		{
			get
			{
				return this._VFX_DateCreated;
			}
			set
			{
				if ((this._VFX_DateCreated != value))
				{
					this._VFX_DateCreated = value;
				}
			}
		}
		
		[Column(Storage="_VFX_DateUpdated", DbType="DateTime NOT NULL")]
		public System.DateTime VFX_DateUpdated
		{
			get
			{
				return this._VFX_DateUpdated;
			}
			set
			{
				if ((this._VFX_DateUpdated != value))
				{
					this._VFX_DateUpdated = value;
				}
			}
		}
		
		[Column(Storage="_VFX_DateDeleted", DbType="DateTime")]
		public System.Nullable<System.DateTime> VFX_DateDeleted
		{
			get
			{
				return this._VFX_DateDeleted;
			}
			set
			{
				if ((this._VFX_DateDeleted != value))
				{
					this._VFX_DateDeleted = value;
				}
			}
		}
		
		[Column(Storage="_InventorySource", DbType="BigInt")]
		public System.Nullable<long> InventorySource
		{
			get
			{
				return this._InventorySource;
			}
			set
			{
				if ((this._InventorySource != value))
				{
					this._InventorySource = value;
				}
			}
		}
		
		[Column(Storage="_CheckFieldName", DbType="NVarChar(32) NOT NULL", CanBeNull=false)]
		public string CheckFieldName
		{
			get
			{
				return this._CheckFieldName;
			}
			set
			{
				if ((this._CheckFieldName != value))
				{
					this._CheckFieldName = value;
				}
			}
		}
		
		[Column(Storage="_CheckFieldValue", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string CheckFieldValue
		{
			get
			{
				return this._CheckFieldValue;
			}
			set
			{
				if ((this._CheckFieldValue != value))
				{
					this._CheckFieldValue = value;
				}
			}
		}
		
		[Column(Storage="_SetFieldName", DbType="NVarChar(32) NOT NULL", CanBeNull=false)]
		public string SetFieldName
		{
			get
			{
				return this._SetFieldName;
			}
			set
			{
				if ((this._SetFieldName != value))
				{
					this._SetFieldName = value;
				}
			}
		}
		
		[Column(Storage="_SetFieldValue", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string SetFieldValue
		{
			get
			{
				return this._SetFieldValue;
			}
			set
			{
				if ((this._SetFieldValue != value))
				{
					this._SetFieldValue = value;
				}
			}
		}
		
		[Column(Storage="_SetFieldDefault", DbType="NVarChar(128)")]
		public string SetFieldDefault
		{
			get
			{
				return this._SetFieldDefault;
			}
			set
			{
				if ((this._SetFieldDefault != value))
				{
					this._SetFieldDefault = value;
				}
			}
		}
		
		[Column(Storage="_CaseSensitive", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string CaseSensitive
		{
			get
			{
				return this._CaseSensitive;
			}
			set
			{
				if ((this._CaseSensitive != value))
				{
					this._CaseSensitive = value;
				}
			}
		}
		
		[Column(Storage="_NoMatchAction", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string NoMatchAction
		{
			get
			{
				return this._NoMatchAction;
			}
			set
			{
				if ((this._NoMatchAction != value))
				{
					this._NoMatchAction = value;
				}
			}
		}
		
		[Column(Storage="_Sequence", DbType="Int")]
		public System.Nullable<int> Sequence
		{
			get
			{
				return this._Sequence;
			}
			set
			{
				if ((this._Sequence != value))
				{
					this._Sequence = value;
				}
			}
		}
		
		[Column(Storage="_Status", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[Column(Storage="_Comments", DbType="NVarChar(256)")]
		public string Comments
		{
			get
			{
				return this._Comments;
			}
			set
			{
				if ((this._Comments != value))
				{
					this._Comments = value;
				}
			}
		}
		
		[Column(Storage="_ETL_NaturalKey", DbType="VarChar(256)")]
		public string ETL_NaturalKey
		{
			get
			{
				return this._ETL_NaturalKey;
			}
			set
			{
				if ((this._ETL_NaturalKey != value))
				{
					this._ETL_NaturalKey = value;
				}
			}
		}
		
		[Column(Storage="_ETL_Hash", DbType="Binary(16)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ETL_Hash
		{
			get
			{
				return this._ETL_Hash;
			}
			set
			{
				if ((this._ETL_Hash != value))
				{
					this._ETL_Hash = value;
				}
			}
		}
		
		[Column(Storage="_ETL_JobCategory", DbType="VarChar(50)")]
		public string ETL_JobCategory
		{
			get
			{
				return this._ETL_JobCategory;
			}
			set
			{
				if ((this._ETL_JobCategory != value))
				{
					this._ETL_JobCategory = value;
				}
			}
		}
		
		[Column(Storage="_ETL_DateEffective", DbType="DateTime")]
		public System.Nullable<System.DateTime> ETL_DateEffective
		{
			get
			{
				return this._ETL_DateEffective;
			}
			set
			{
				if ((this._ETL_DateEffective != value))
				{
					this._ETL_DateEffective = value;
				}
			}
		}
	}
	
	[Table(Name="InventoryImport.InventoryAccountTable")]
	public partial class InventoryAccountTable
	{
		
		private long _ID;
		
		private System.Nullable<long> _VFX_CreatorID;
		
		private System.Nullable<long> _VFX_UpdaterID;
		
		private System.Nullable<long> _VFX_DeletorID;
		
		private System.DateTime _VFX_DateCreated;
		
		private System.DateTime _VFX_DateUpdated;
		
		private System.Nullable<System.DateTime> _VFX_DateDeleted;
		
		private string _Account;
		
		private System.Nullable<int> _VehicleType;
		
		private System.Nullable<long> _SellerInfo;
		
		private System.Nullable<long> _InventorySource;
		
		private string _ETL_NaturalKey;
		
		private System.Data.Linq.Binary _ETL_Hash;
		
		private string _ETL_JobCategory;
		
		private System.Nullable<System.DateTime> _ETL_DateEffective;
		
		public InventoryAccountTable()
		{
		}
		
		[Column(Storage="_ID", DbType="BigInt NOT NULL")]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[Column(Storage="_VFX_CreatorID", DbType="BigInt")]
		public System.Nullable<long> VFX_CreatorID
		{
			get
			{
				return this._VFX_CreatorID;
			}
			set
			{
				if ((this._VFX_CreatorID != value))
				{
					this._VFX_CreatorID = value;
				}
			}
		}
		
		[Column(Storage="_VFX_UpdaterID", DbType="BigInt")]
		public System.Nullable<long> VFX_UpdaterID
		{
			get
			{
				return this._VFX_UpdaterID;
			}
			set
			{
				if ((this._VFX_UpdaterID != value))
				{
					this._VFX_UpdaterID = value;
				}
			}
		}
		
		[Column(Storage="_VFX_DeletorID", DbType="BigInt")]
		public System.Nullable<long> VFX_DeletorID
		{
			get
			{
				return this._VFX_DeletorID;
			}
			set
			{
				if ((this._VFX_DeletorID != value))
				{
					this._VFX_DeletorID = value;
				}
			}
		}
		
		[Column(Storage="_VFX_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime VFX_DateCreated
		{
			get
			{
				return this._VFX_DateCreated;
			}
			set
			{
				if ((this._VFX_DateCreated != value))
				{
					this._VFX_DateCreated = value;
				}
			}
		}
		
		[Column(Storage="_VFX_DateUpdated", DbType="DateTime NOT NULL")]
		public System.DateTime VFX_DateUpdated
		{
			get
			{
				return this._VFX_DateUpdated;
			}
			set
			{
				if ((this._VFX_DateUpdated != value))
				{
					this._VFX_DateUpdated = value;
				}
			}
		}
		
		[Column(Storage="_VFX_DateDeleted", DbType="DateTime")]
		public System.Nullable<System.DateTime> VFX_DateDeleted
		{
			get
			{
				return this._VFX_DateDeleted;
			}
			set
			{
				if ((this._VFX_DateDeleted != value))
				{
					this._VFX_DateDeleted = value;
				}
			}
		}
		
		[Column(Storage="_Account", DbType="NVarChar(32)")]
		public string Account
		{
			get
			{
				return this._Account;
			}
			set
			{
				if ((this._Account != value))
				{
					this._Account = value;
				}
			}
		}
		
		[Column(Storage="_VehicleType", DbType="Int")]
		public System.Nullable<int> VehicleType
		{
			get
			{
				return this._VehicleType;
			}
			set
			{
				if ((this._VehicleType != value))
				{
					this._VehicleType = value;
				}
			}
		}
		
		[Column(Storage="_SellerInfo", DbType="BigInt")]
		public System.Nullable<long> SellerInfo
		{
			get
			{
				return this._SellerInfo;
			}
			set
			{
				if ((this._SellerInfo != value))
				{
					this._SellerInfo = value;
				}
			}
		}
		
		[Column(Storage="_InventorySource", DbType="BigInt")]
		public System.Nullable<long> InventorySource
		{
			get
			{
				return this._InventorySource;
			}
			set
			{
				if ((this._InventorySource != value))
				{
					this._InventorySource = value;
				}
			}
		}
		
		[Column(Storage="_ETL_NaturalKey", DbType="VarChar(256)")]
		public string ETL_NaturalKey
		{
			get
			{
				return this._ETL_NaturalKey;
			}
			set
			{
				if ((this._ETL_NaturalKey != value))
				{
					this._ETL_NaturalKey = value;
				}
			}
		}
		
		[Column(Storage="_ETL_Hash", DbType="Binary(16)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ETL_Hash
		{
			get
			{
				return this._ETL_Hash;
			}
			set
			{
				if ((this._ETL_Hash != value))
				{
					this._ETL_Hash = value;
				}
			}
		}
		
		[Column(Storage="_ETL_JobCategory", DbType="VarChar(50)")]
		public string ETL_JobCategory
		{
			get
			{
				return this._ETL_JobCategory;
			}
			set
			{
				if ((this._ETL_JobCategory != value))
				{
					this._ETL_JobCategory = value;
				}
			}
		}
		
		[Column(Storage="_ETL_DateEffective", DbType="DateTime")]
		public System.Nullable<System.DateTime> ETL_DateEffective
		{
			get
			{
				return this._ETL_DateEffective;
			}
			set
			{
				if ((this._ETL_DateEffective != value))
				{
					this._ETL_DateEffective = value;
				}
			}
		}
	}
	
	[Table(Name="InventoryImport.InventorySourceTable")]
	public partial class InventorySourceTable
	{
		
		private long _ID;
		
		private System.Nullable<long> _VFX_CreatorID;
		
		private System.Nullable<long> _VFX_UpdaterID;
		
		private System.Nullable<long> _VFX_DeletorID;
		
		private System.DateTime _VFX_DateCreated;
		
		private System.DateTime _VFX_DateUpdated;
		
		private System.Nullable<System.DateTime> _VFX_DateDeleted;
		
		private string _FileName;
		
		private System.Nullable<int> _FileDelimiter;
		
		private string _TextQualifier;
		
		private System.Nullable<long> _FileColumn;
		
		private string _InventorySystem;
		
		private string _ETL_NaturalKey;
		
		private System.Data.Linq.Binary _ETL_Hash;
		
		private string _ETL_JobCategory;
		
		private System.Nullable<System.DateTime> _ETL_DateEffective;
		
		private string _UseImageUrl;
		
		public InventorySourceTable()
		{
		}
		
		[Column(Storage="_ID", DbType="BigInt NOT NULL")]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[Column(Storage="_VFX_CreatorID", DbType="BigInt")]
		public System.Nullable<long> VFX_CreatorID
		{
			get
			{
				return this._VFX_CreatorID;
			}
			set
			{
				if ((this._VFX_CreatorID != value))
				{
					this._VFX_CreatorID = value;
				}
			}
		}
		
		[Column(Storage="_VFX_UpdaterID", DbType="BigInt")]
		public System.Nullable<long> VFX_UpdaterID
		{
			get
			{
				return this._VFX_UpdaterID;
			}
			set
			{
				if ((this._VFX_UpdaterID != value))
				{
					this._VFX_UpdaterID = value;
				}
			}
		}
		
		[Column(Storage="_VFX_DeletorID", DbType="BigInt")]
		public System.Nullable<long> VFX_DeletorID
		{
			get
			{
				return this._VFX_DeletorID;
			}
			set
			{
				if ((this._VFX_DeletorID != value))
				{
					this._VFX_DeletorID = value;
				}
			}
		}
		
		[Column(Storage="_VFX_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime VFX_DateCreated
		{
			get
			{
				return this._VFX_DateCreated;
			}
			set
			{
				if ((this._VFX_DateCreated != value))
				{
					this._VFX_DateCreated = value;
				}
			}
		}
		
		[Column(Storage="_VFX_DateUpdated", DbType="DateTime NOT NULL")]
		public System.DateTime VFX_DateUpdated
		{
			get
			{
				return this._VFX_DateUpdated;
			}
			set
			{
				if ((this._VFX_DateUpdated != value))
				{
					this._VFX_DateUpdated = value;
				}
			}
		}
		
		[Column(Storage="_VFX_DateDeleted", DbType="DateTime")]
		public System.Nullable<System.DateTime> VFX_DateDeleted
		{
			get
			{
				return this._VFX_DateDeleted;
			}
			set
			{
				if ((this._VFX_DateDeleted != value))
				{
					this._VFX_DateDeleted = value;
				}
			}
		}
		
		[Column(Storage="_FileName", DbType="NVarChar(32) NOT NULL", CanBeNull=false)]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this._FileName = value;
				}
			}
		}
		
		[Column(Storage="_FileDelimiter", DbType="Int")]
		public System.Nullable<int> FileDelimiter
		{
			get
			{
				return this._FileDelimiter;
			}
			set
			{
				if ((this._FileDelimiter != value))
				{
					this._FileDelimiter = value;
				}
			}
		}
		
		[Column(Storage="_TextQualifier", DbType="NVarChar(32)")]
		public string TextQualifier
		{
			get
			{
				return this._TextQualifier;
			}
			set
			{
				if ((this._TextQualifier != value))
				{
					this._TextQualifier = value;
				}
			}
		}
		
		[Column(Storage="_FileColumn", DbType="BigInt")]
		public System.Nullable<long> FileColumn
		{
			get
			{
				return this._FileColumn;
			}
			set
			{
				if ((this._FileColumn != value))
				{
					this._FileColumn = value;
				}
			}
		}
		
		[Column(Storage="_InventorySystem", DbType="NVarChar(64)")]
		public string InventorySystem
		{
			get
			{
				return this._InventorySystem;
			}
			set
			{
				if ((this._InventorySystem != value))
				{
					this._InventorySystem = value;
				}
			}
		}
		
		[Column(Storage="_ETL_NaturalKey", DbType="VarChar(256)")]
		public string ETL_NaturalKey
		{
			get
			{
				return this._ETL_NaturalKey;
			}
			set
			{
				if ((this._ETL_NaturalKey != value))
				{
					this._ETL_NaturalKey = value;
				}
			}
		}
		
		[Column(Storage="_ETL_Hash", DbType="Binary(16)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ETL_Hash
		{
			get
			{
				return this._ETL_Hash;
			}
			set
			{
				if ((this._ETL_Hash != value))
				{
					this._ETL_Hash = value;
				}
			}
		}
		
		[Column(Storage="_ETL_JobCategory", DbType="VarChar(50)")]
		public string ETL_JobCategory
		{
			get
			{
				return this._ETL_JobCategory;
			}
			set
			{
				if ((this._ETL_JobCategory != value))
				{
					this._ETL_JobCategory = value;
				}
			}
		}
		
		[Column(Storage="_ETL_DateEffective", DbType="DateTime")]
		public System.Nullable<System.DateTime> ETL_DateEffective
		{
			get
			{
				return this._ETL_DateEffective;
			}
			set
			{
				if ((this._ETL_DateEffective != value))
				{
					this._ETL_DateEffective = value;
				}
			}
		}
		
		[Column(Storage="_UseImageUrl", DbType="NVarChar(9)")]
		public string UseImageUrl
		{
			get
			{
				return this._UseImageUrl;
			}
			set
			{
				if ((this._UseImageUrl != value))
				{
					this._UseImageUrl = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
