#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nathandelane.WatiN.VehixTesting.Data.VehixFoundation
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="VehixFoundation")]
	public partial class VehixFoundationSellYourCarDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertListingPackageTable(ListingPackageTable instance);
    partial void UpdateListingPackageTable(ListingPackageTable instance);
    partial void DeleteListingPackageTable(ListingPackageTable instance);
    #endregion
		
		public VehixFoundationSellYourCarDataContext() : 
				base(global::Nathandelane.WatiN.VehixTesting.Data.Properties.Settings.Default.VehixFoundationConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public VehixFoundationSellYourCarDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VehixFoundationSellYourCarDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VehixFoundationSellYourCarDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VehixFoundationSellYourCarDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ListingPackageTable> ListingPackageTables
		{
			get
			{
				return this.GetTable<ListingPackageTable>();
			}
		}
		
		public System.Data.Linq.Table<SellYourCarProductTable> SellYourCarProductTables
		{
			get
			{
				return this.GetTable<SellYourCarProductTable>();
			}
		}
		
		public System.Data.Linq.Table<ListingTable> ListingTables
		{
			get
			{
				return this.GetTable<ListingTable>();
			}
		}
		
		public System.Data.Linq.Table<ListingTransactionTable> ListingTransactionTables
		{
			get
			{
				return this.GetTable<ListingTransactionTable>();
			}
		}
		
		public System.Data.Linq.Table<PrivateSellerOptionsTable> PrivateSellerOptionsTables
		{
			get
			{
				return this.GetTable<PrivateSellerOptionsTable>();
			}
		}
	}
	
	[Table(Name="SellYourCar.ListingPackageTable")]
	public partial class ListingPackageTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private long _VFX_CreatorID;
		
		private long _VFX_UpdaterID;
		
		private System.Nullable<long> _VFX_DeletorID;
		
		private System.DateTime _VFX_DateCreated;
		
		private System.DateTime _VFX_DateUpdated;
		
		private System.Nullable<System.DateTime> _VFX_DateDeleted;
		
		private string _GroupName;
		
		private int _Sequence;
		
		private string _Name;
		
		private int _AllowedPhotos;
		
		private string _InventoryCatalog;
		
		private string _SellerPriorityName;
		
		private int _SellerPriorityLevel;
		
		private string _ListingPriorityName;
		
		private int _ListingPriorityLevel;
		
		private string _BrandingPackageCompatibility;
		
		private string _HasExpiration;
		
		private decimal _Price;
		
		private System.Nullable<int> _ExpirationInDays;
		
		private int _RenewalInDays;
		
		private string _PurchaseTemplate;
		
		private string _EditTemplate;
		
		private string _ETL_NaturalKey;
		
		private System.Data.Linq.Binary _ETL_Hash;
		
		private string _ETL_JobCategory;
		
		private System.Nullable<System.DateTime> _ETL_DateEffective;
		
		private long _Locale;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnVFX_CreatorIDChanging(long value);
    partial void OnVFX_CreatorIDChanged();
    partial void OnVFX_UpdaterIDChanging(long value);
    partial void OnVFX_UpdaterIDChanged();
    partial void OnVFX_DeletorIDChanging(System.Nullable<long> value);
    partial void OnVFX_DeletorIDChanged();
    partial void OnVFX_DateCreatedChanging(System.DateTime value);
    partial void OnVFX_DateCreatedChanged();
    partial void OnVFX_DateUpdatedChanging(System.DateTime value);
    partial void OnVFX_DateUpdatedChanged();
    partial void OnVFX_DateDeletedChanging(System.Nullable<System.DateTime> value);
    partial void OnVFX_DateDeletedChanged();
    partial void OnGroupNameChanging(string value);
    partial void OnGroupNameChanged();
    partial void OnSequenceChanging(int value);
    partial void OnSequenceChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnAllowedPhotosChanging(int value);
    partial void OnAllowedPhotosChanged();
    partial void OnInventoryCatalogChanging(string value);
    partial void OnInventoryCatalogChanged();
    partial void OnSellerPriorityNameChanging(string value);
    partial void OnSellerPriorityNameChanged();
    partial void OnSellerPriorityLevelChanging(int value);
    partial void OnSellerPriorityLevelChanged();
    partial void OnListingPriorityNameChanging(string value);
    partial void OnListingPriorityNameChanged();
    partial void OnListingPriorityLevelChanging(int value);
    partial void OnListingPriorityLevelChanged();
    partial void OnBrandingPackageCompatibilityChanging(string value);
    partial void OnBrandingPackageCompatibilityChanged();
    partial void OnHasExpirationChanging(string value);
    partial void OnHasExpirationChanged();
    partial void OnPriceChanging(decimal value);
    partial void OnPriceChanged();
    partial void OnExpirationInDaysChanging(System.Nullable<int> value);
    partial void OnExpirationInDaysChanged();
    partial void OnRenewalInDaysChanging(int value);
    partial void OnRenewalInDaysChanged();
    partial void OnPurchaseTemplateChanging(string value);
    partial void OnPurchaseTemplateChanged();
    partial void OnEditTemplateChanging(string value);
    partial void OnEditTemplateChanged();
    partial void OnETL_NaturalKeyChanging(string value);
    partial void OnETL_NaturalKeyChanged();
    partial void OnETL_HashChanging(System.Data.Linq.Binary value);
    partial void OnETL_HashChanged();
    partial void OnETL_JobCategoryChanging(string value);
    partial void OnETL_JobCategoryChanged();
    partial void OnETL_DateEffectiveChanging(System.Nullable<System.DateTime> value);
    partial void OnETL_DateEffectiveChanged();
    partial void OnLocaleChanging(long value);
    partial void OnLocaleChanged();
    #endregion
		
		public ListingPackageTable()
		{
			OnCreated();
		}
		
		[Column(Storage="_ID", DbType="BigInt NOT NULL")]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_VFX_CreatorID", DbType="BigInt NOT NULL")]
		public long VFX_CreatorID
		{
			get
			{
				return this._VFX_CreatorID;
			}
			set
			{
				if ((this._VFX_CreatorID != value))
				{
					this.OnVFX_CreatorIDChanging(value);
					this.SendPropertyChanging();
					this._VFX_CreatorID = value;
					this.SendPropertyChanged("VFX_CreatorID");
					this.OnVFX_CreatorIDChanged();
				}
			}
		}
		
		[Column(Storage="_VFX_UpdaterID", DbType="BigInt NOT NULL")]
		public long VFX_UpdaterID
		{
			get
			{
				return this._VFX_UpdaterID;
			}
			set
			{
				if ((this._VFX_UpdaterID != value))
				{
					this.OnVFX_UpdaterIDChanging(value);
					this.SendPropertyChanging();
					this._VFX_UpdaterID = value;
					this.SendPropertyChanged("VFX_UpdaterID");
					this.OnVFX_UpdaterIDChanged();
				}
			}
		}
		
		[Column(Storage="_VFX_DeletorID", DbType="BigInt")]
		public System.Nullable<long> VFX_DeletorID
		{
			get
			{
				return this._VFX_DeletorID;
			}
			set
			{
				if ((this._VFX_DeletorID != value))
				{
					this.OnVFX_DeletorIDChanging(value);
					this.SendPropertyChanging();
					this._VFX_DeletorID = value;
					this.SendPropertyChanged("VFX_DeletorID");
					this.OnVFX_DeletorIDChanged();
				}
			}
		}
		
		[Column(Storage="_VFX_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime VFX_DateCreated
		{
			get
			{
				return this._VFX_DateCreated;
			}
			set
			{
				if ((this._VFX_DateCreated != value))
				{
					this.OnVFX_DateCreatedChanging(value);
					this.SendPropertyChanging();
					this._VFX_DateCreated = value;
					this.SendPropertyChanged("VFX_DateCreated");
					this.OnVFX_DateCreatedChanged();
				}
			}
		}
		
		[Column(Storage="_VFX_DateUpdated", DbType="DateTime NOT NULL")]
		public System.DateTime VFX_DateUpdated
		{
			get
			{
				return this._VFX_DateUpdated;
			}
			set
			{
				if ((this._VFX_DateUpdated != value))
				{
					this.OnVFX_DateUpdatedChanging(value);
					this.SendPropertyChanging();
					this._VFX_DateUpdated = value;
					this.SendPropertyChanged("VFX_DateUpdated");
					this.OnVFX_DateUpdatedChanged();
				}
			}
		}
		
		[Column(Storage="_VFX_DateDeleted", DbType="DateTime")]
		public System.Nullable<System.DateTime> VFX_DateDeleted
		{
			get
			{
				return this._VFX_DateDeleted;
			}
			set
			{
				if ((this._VFX_DateDeleted != value))
				{
					this.OnVFX_DateDeletedChanging(value);
					this.SendPropertyChanging();
					this._VFX_DateDeleted = value;
					this.SendPropertyChanged("VFX_DateDeleted");
					this.OnVFX_DateDeletedChanged();
				}
			}
		}
		
		[Column(Storage="_GroupName", DbType="NVarChar(40) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string GroupName
		{
			get
			{
				return this._GroupName;
			}
			set
			{
				if ((this._GroupName != value))
				{
					this.OnGroupNameChanging(value);
					this.SendPropertyChanging();
					this._GroupName = value;
					this.SendPropertyChanged("GroupName");
					this.OnGroupNameChanged();
				}
			}
		}
		
		[Column(Storage="_Sequence", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Sequence
		{
			get
			{
				return this._Sequence;
			}
			set
			{
				if ((this._Sequence != value))
				{
					this.OnSequenceChanging(value);
					this.SendPropertyChanging();
					this._Sequence = value;
					this.SendPropertyChanged("Sequence");
					this.OnSequenceChanged();
				}
			}
		}
		
		[Column(Storage="_Name", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[Column(Storage="_AllowedPhotos", DbType="Int NOT NULL")]
		public int AllowedPhotos
		{
			get
			{
				return this._AllowedPhotos;
			}
			set
			{
				if ((this._AllowedPhotos != value))
				{
					this.OnAllowedPhotosChanging(value);
					this.SendPropertyChanging();
					this._AllowedPhotos = value;
					this.SendPropertyChanged("AllowedPhotos");
					this.OnAllowedPhotosChanged();
				}
			}
		}
		
		[Column(Storage="_InventoryCatalog", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string InventoryCatalog
		{
			get
			{
				return this._InventoryCatalog;
			}
			set
			{
				if ((this._InventoryCatalog != value))
				{
					this.OnInventoryCatalogChanging(value);
					this.SendPropertyChanging();
					this._InventoryCatalog = value;
					this.SendPropertyChanged("InventoryCatalog");
					this.OnInventoryCatalogChanged();
				}
			}
		}
		
		[Column(Storage="_SellerPriorityName", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string SellerPriorityName
		{
			get
			{
				return this._SellerPriorityName;
			}
			set
			{
				if ((this._SellerPriorityName != value))
				{
					this.OnSellerPriorityNameChanging(value);
					this.SendPropertyChanging();
					this._SellerPriorityName = value;
					this.SendPropertyChanged("SellerPriorityName");
					this.OnSellerPriorityNameChanged();
				}
			}
		}
		
		[Column(Storage="_SellerPriorityLevel", DbType="Int NOT NULL")]
		public int SellerPriorityLevel
		{
			get
			{
				return this._SellerPriorityLevel;
			}
			set
			{
				if ((this._SellerPriorityLevel != value))
				{
					this.OnSellerPriorityLevelChanging(value);
					this.SendPropertyChanging();
					this._SellerPriorityLevel = value;
					this.SendPropertyChanged("SellerPriorityLevel");
					this.OnSellerPriorityLevelChanged();
				}
			}
		}
		
		[Column(Storage="_ListingPriorityName", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string ListingPriorityName
		{
			get
			{
				return this._ListingPriorityName;
			}
			set
			{
				if ((this._ListingPriorityName != value))
				{
					this.OnListingPriorityNameChanging(value);
					this.SendPropertyChanging();
					this._ListingPriorityName = value;
					this.SendPropertyChanged("ListingPriorityName");
					this.OnListingPriorityNameChanged();
				}
			}
		}
		
		[Column(Storage="_ListingPriorityLevel", DbType="Int NOT NULL")]
		public int ListingPriorityLevel
		{
			get
			{
				return this._ListingPriorityLevel;
			}
			set
			{
				if ((this._ListingPriorityLevel != value))
				{
					this.OnListingPriorityLevelChanging(value);
					this.SendPropertyChanging();
					this._ListingPriorityLevel = value;
					this.SendPropertyChanged("ListingPriorityLevel");
					this.OnListingPriorityLevelChanged();
				}
			}
		}
		
		[Column(Storage="_BrandingPackageCompatibility", DbType="NVarChar(12)")]
		public string BrandingPackageCompatibility
		{
			get
			{
				return this._BrandingPackageCompatibility;
			}
			set
			{
				if ((this._BrandingPackageCompatibility != value))
				{
					this.OnBrandingPackageCompatibilityChanging(value);
					this.SendPropertyChanging();
					this._BrandingPackageCompatibility = value;
					this.SendPropertyChanged("BrandingPackageCompatibility");
					this.OnBrandingPackageCompatibilityChanged();
				}
			}
		}
		
		[Column(Storage="_HasExpiration", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string HasExpiration
		{
			get
			{
				return this._HasExpiration;
			}
			set
			{
				if ((this._HasExpiration != value))
				{
					this.OnHasExpirationChanging(value);
					this.SendPropertyChanging();
					this._HasExpiration = value;
					this.SendPropertyChanged("HasExpiration");
					this.OnHasExpirationChanged();
				}
			}
		}
		
		[Column(Storage="_Price", DbType="Decimal(10,2) NOT NULL")]
		public decimal Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[Column(Storage="_ExpirationInDays", DbType="Int")]
		public System.Nullable<int> ExpirationInDays
		{
			get
			{
				return this._ExpirationInDays;
			}
			set
			{
				if ((this._ExpirationInDays != value))
				{
					this.OnExpirationInDaysChanging(value);
					this.SendPropertyChanging();
					this._ExpirationInDays = value;
					this.SendPropertyChanged("ExpirationInDays");
					this.OnExpirationInDaysChanged();
				}
			}
		}
		
		[Column(Storage="_RenewalInDays", DbType="Int NOT NULL")]
		public int RenewalInDays
		{
			get
			{
				return this._RenewalInDays;
			}
			set
			{
				if ((this._RenewalInDays != value))
				{
					this.OnRenewalInDaysChanging(value);
					this.SendPropertyChanging();
					this._RenewalInDays = value;
					this.SendPropertyChanged("RenewalInDays");
					this.OnRenewalInDaysChanged();
				}
			}
		}
		
		[Column(Storage="_PurchaseTemplate", DbType="NVarChar(400) NOT NULL", CanBeNull=false)]
		public string PurchaseTemplate
		{
			get
			{
				return this._PurchaseTemplate;
			}
			set
			{
				if ((this._PurchaseTemplate != value))
				{
					this.OnPurchaseTemplateChanging(value);
					this.SendPropertyChanging();
					this._PurchaseTemplate = value;
					this.SendPropertyChanged("PurchaseTemplate");
					this.OnPurchaseTemplateChanged();
				}
			}
		}
		
		[Column(Storage="_EditTemplate", DbType="NVarChar(400) NOT NULL", CanBeNull=false)]
		public string EditTemplate
		{
			get
			{
				return this._EditTemplate;
			}
			set
			{
				if ((this._EditTemplate != value))
				{
					this.OnEditTemplateChanging(value);
					this.SendPropertyChanging();
					this._EditTemplate = value;
					this.SendPropertyChanged("EditTemplate");
					this.OnEditTemplateChanged();
				}
			}
		}
		
		[Column(Storage="_ETL_NaturalKey", DbType="VarChar(256)")]
		public string ETL_NaturalKey
		{
			get
			{
				return this._ETL_NaturalKey;
			}
			set
			{
				if ((this._ETL_NaturalKey != value))
				{
					this.OnETL_NaturalKeyChanging(value);
					this.SendPropertyChanging();
					this._ETL_NaturalKey = value;
					this.SendPropertyChanged("ETL_NaturalKey");
					this.OnETL_NaturalKeyChanged();
				}
			}
		}
		
		[Column(Storage="_ETL_Hash", DbType="Binary(16)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ETL_Hash
		{
			get
			{
				return this._ETL_Hash;
			}
			set
			{
				if ((this._ETL_Hash != value))
				{
					this.OnETL_HashChanging(value);
					this.SendPropertyChanging();
					this._ETL_Hash = value;
					this.SendPropertyChanged("ETL_Hash");
					this.OnETL_HashChanged();
				}
			}
		}
		
		[Column(Storage="_ETL_JobCategory", DbType="VarChar(50)")]
		public string ETL_JobCategory
		{
			get
			{
				return this._ETL_JobCategory;
			}
			set
			{
				if ((this._ETL_JobCategory != value))
				{
					this.OnETL_JobCategoryChanging(value);
					this.SendPropertyChanging();
					this._ETL_JobCategory = value;
					this.SendPropertyChanged("ETL_JobCategory");
					this.OnETL_JobCategoryChanged();
				}
			}
		}
		
		[Column(Storage="_ETL_DateEffective", DbType="DateTime")]
		public System.Nullable<System.DateTime> ETL_DateEffective
		{
			get
			{
				return this._ETL_DateEffective;
			}
			set
			{
				if ((this._ETL_DateEffective != value))
				{
					this.OnETL_DateEffectiveChanging(value);
					this.SendPropertyChanging();
					this._ETL_DateEffective = value;
					this.SendPropertyChanged("ETL_DateEffective");
					this.OnETL_DateEffectiveChanged();
				}
			}
		}
		
		[Column(Storage="_Locale", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Locale
		{
			get
			{
				return this._Locale;
			}
			set
			{
				if ((this._Locale != value))
				{
					this.OnLocaleChanging(value);
					this.SendPropertyChanging();
					this._Locale = value;
					this.SendPropertyChanged("Locale");
					this.OnLocaleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="SellYourCar.SellYourCarProductTable")]
	public partial class SellYourCarProductTable
	{
		
		private long _ID;
		
		private string _DisplayPhoneNumber;
		
		private long _Package;
		
		private string _ETL_NaturalKey;
		
		private System.Data.Linq.Binary _ETL_Hash;
		
		private string _ETL_JobCategory;
		
		private System.Nullable<System.DateTime> _ETL_DateEffective;
		
		public SellYourCarProductTable()
		{
		}
		
		[Column(Storage="_ID", DbType="BigInt NOT NULL")]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[Column(Storage="_DisplayPhoneNumber", DbType="Char(5)")]
		public string DisplayPhoneNumber
		{
			get
			{
				return this._DisplayPhoneNumber;
			}
			set
			{
				if ((this._DisplayPhoneNumber != value))
				{
					this._DisplayPhoneNumber = value;
				}
			}
		}
		
		[Column(Storage="_Package", DbType="BigInt NOT NULL")]
		public long Package
		{
			get
			{
				return this._Package;
			}
			set
			{
				if ((this._Package != value))
				{
					this._Package = value;
				}
			}
		}
		
		[Column(Storage="_ETL_NaturalKey", DbType="VarChar(256)")]
		public string ETL_NaturalKey
		{
			get
			{
				return this._ETL_NaturalKey;
			}
			set
			{
				if ((this._ETL_NaturalKey != value))
				{
					this._ETL_NaturalKey = value;
				}
			}
		}
		
		[Column(Storage="_ETL_Hash", DbType="Binary(16)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ETL_Hash
		{
			get
			{
				return this._ETL_Hash;
			}
			set
			{
				if ((this._ETL_Hash != value))
				{
					this._ETL_Hash = value;
				}
			}
		}
		
		[Column(Storage="_ETL_JobCategory", DbType="VarChar(50)")]
		public string ETL_JobCategory
		{
			get
			{
				return this._ETL_JobCategory;
			}
			set
			{
				if ((this._ETL_JobCategory != value))
				{
					this._ETL_JobCategory = value;
				}
			}
		}
		
		[Column(Storage="_ETL_DateEffective", DbType="DateTime")]
		public System.Nullable<System.DateTime> ETL_DateEffective
		{
			get
			{
				return this._ETL_DateEffective;
			}
			set
			{
				if ((this._ETL_DateEffective != value))
				{
					this._ETL_DateEffective = value;
				}
			}
		}
	}
	
	[Table(Name="SellYourCar.ListingTable")]
	public partial class ListingTable
	{
		
		private long _ID;
		
		private System.Nullable<long> _VFX_CreatorID;
		
		private System.Nullable<long> _VFX_UpdaterID;
		
		private System.Nullable<long> _VFX_DeletorID;
		
		private System.DateTime _VFX_DateCreated;
		
		private System.DateTime _VFX_DateUpdated;
		
		private System.Nullable<System.DateTime> _VFX_DateDeleted;
		
		private string _Test;
		
		private long _Vehicle;
		
		private string _ETL_NaturalKey;
		
		private System.Data.Linq.Binary _ETL_Hash;
		
		private string _ETL_JobCategory;
		
		private System.Nullable<System.DateTime> _ETL_DateEffective;
		
		private string _Uri;
		
		private string _QuarantinedByVehixReason;
		
		private string _IPAddress;
		
		public ListingTable()
		{
		}
		
		[Column(Storage="_ID", DbType="BigInt NOT NULL")]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[Column(Storage="_VFX_CreatorID", DbType="BigInt")]
		public System.Nullable<long> VFX_CreatorID
		{
			get
			{
				return this._VFX_CreatorID;
			}
			set
			{
				if ((this._VFX_CreatorID != value))
				{
					this._VFX_CreatorID = value;
				}
			}
		}
		
		[Column(Storage="_VFX_UpdaterID", DbType="BigInt")]
		public System.Nullable<long> VFX_UpdaterID
		{
			get
			{
				return this._VFX_UpdaterID;
			}
			set
			{
				if ((this._VFX_UpdaterID != value))
				{
					this._VFX_UpdaterID = value;
				}
			}
		}
		
		[Column(Storage="_VFX_DeletorID", DbType="BigInt")]
		public System.Nullable<long> VFX_DeletorID
		{
			get
			{
				return this._VFX_DeletorID;
			}
			set
			{
				if ((this._VFX_DeletorID != value))
				{
					this._VFX_DeletorID = value;
				}
			}
		}
		
		[Column(Storage="_VFX_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime VFX_DateCreated
		{
			get
			{
				return this._VFX_DateCreated;
			}
			set
			{
				if ((this._VFX_DateCreated != value))
				{
					this._VFX_DateCreated = value;
				}
			}
		}
		
		[Column(Storage="_VFX_DateUpdated", DbType="DateTime NOT NULL")]
		public System.DateTime VFX_DateUpdated
		{
			get
			{
				return this._VFX_DateUpdated;
			}
			set
			{
				if ((this._VFX_DateUpdated != value))
				{
					this._VFX_DateUpdated = value;
				}
			}
		}
		
		[Column(Storage="_VFX_DateDeleted", DbType="DateTime")]
		public System.Nullable<System.DateTime> VFX_DateDeleted
		{
			get
			{
				return this._VFX_DateDeleted;
			}
			set
			{
				if ((this._VFX_DateDeleted != value))
				{
					this._VFX_DateDeleted = value;
				}
			}
		}
		
		[Column(Storage="_Test", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string Test
		{
			get
			{
				return this._Test;
			}
			set
			{
				if ((this._Test != value))
				{
					this._Test = value;
				}
			}
		}
		
		[Column(Storage="_Vehicle", DbType="BigInt NOT NULL")]
		public long Vehicle
		{
			get
			{
				return this._Vehicle;
			}
			set
			{
				if ((this._Vehicle != value))
				{
					this._Vehicle = value;
				}
			}
		}
		
		[Column(Storage="_ETL_NaturalKey", DbType="VarChar(256)")]
		public string ETL_NaturalKey
		{
			get
			{
				return this._ETL_NaturalKey;
			}
			set
			{
				if ((this._ETL_NaturalKey != value))
				{
					this._ETL_NaturalKey = value;
				}
			}
		}
		
		[Column(Storage="_ETL_Hash", DbType="Binary(16)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ETL_Hash
		{
			get
			{
				return this._ETL_Hash;
			}
			set
			{
				if ((this._ETL_Hash != value))
				{
					this._ETL_Hash = value;
				}
			}
		}
		
		[Column(Storage="_ETL_JobCategory", DbType="VarChar(50)")]
		public string ETL_JobCategory
		{
			get
			{
				return this._ETL_JobCategory;
			}
			set
			{
				if ((this._ETL_JobCategory != value))
				{
					this._ETL_JobCategory = value;
				}
			}
		}
		
		[Column(Storage="_ETL_DateEffective", DbType="DateTime")]
		public System.Nullable<System.DateTime> ETL_DateEffective
		{
			get
			{
				return this._ETL_DateEffective;
			}
			set
			{
				if ((this._ETL_DateEffective != value))
				{
					this._ETL_DateEffective = value;
				}
			}
		}
		
		[Column(Storage="_Uri", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string Uri
		{
			get
			{
				return this._Uri;
			}
			set
			{
				if ((this._Uri != value))
				{
					this._Uri = value;
				}
			}
		}
		
		[Column(Storage="_QuarantinedByVehixReason", DbType="NVarChar(128)")]
		public string QuarantinedByVehixReason
		{
			get
			{
				return this._QuarantinedByVehixReason;
			}
			set
			{
				if ((this._QuarantinedByVehixReason != value))
				{
					this._QuarantinedByVehixReason = value;
				}
			}
		}
		
		[Column(Storage="_IPAddress", DbType="NVarChar(15)")]
		public string IPAddress
		{
			get
			{
				return this._IPAddress;
			}
			set
			{
				if ((this._IPAddress != value))
				{
					this._IPAddress = value;
				}
			}
		}
	}
	
	[Table(Name="SellYourCar.ListingTransactionTable")]
	public partial class ListingTransactionTable
	{
		
		private long _ID;
		
		private long _VFX_CreatorID;
		
		private long _VFX_UpdaterID;
		
		private System.Nullable<long> _VFX_DeletorID;
		
		private System.DateTime _VFX_DateCreated;
		
		private System.DateTime _VFX_DateUpdated;
		
		private System.Nullable<System.DateTime> _VFX_DateDeleted;
		
		private long _Seller;
		
		private long _Package;
		
		private string _CommitStatus;
		
		private System.Nullable<long> _Vehicle;
		
		private System.Nullable<long> _Account;
		
		private System.Nullable<long> _TransactionResponse;
		
		private System.Guid _SessionKey;
		
		private string _ETL_NaturalKey;
		
		private System.Data.Linq.Binary _ETL_Hash;
		
		private string _ETL_JobCategory;
		
		private System.Nullable<System.DateTime> _ETL_DateEffective;
		
		public ListingTransactionTable()
		{
		}
		
		[Column(Storage="_ID", DbType="BigInt NOT NULL")]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[Column(Storage="_VFX_CreatorID", DbType="BigInt NOT NULL")]
		public long VFX_CreatorID
		{
			get
			{
				return this._VFX_CreatorID;
			}
			set
			{
				if ((this._VFX_CreatorID != value))
				{
					this._VFX_CreatorID = value;
				}
			}
		}
		
		[Column(Storage="_VFX_UpdaterID", DbType="BigInt NOT NULL")]
		public long VFX_UpdaterID
		{
			get
			{
				return this._VFX_UpdaterID;
			}
			set
			{
				if ((this._VFX_UpdaterID != value))
				{
					this._VFX_UpdaterID = value;
				}
			}
		}
		
		[Column(Storage="_VFX_DeletorID", DbType="BigInt")]
		public System.Nullable<long> VFX_DeletorID
		{
			get
			{
				return this._VFX_DeletorID;
			}
			set
			{
				if ((this._VFX_DeletorID != value))
				{
					this._VFX_DeletorID = value;
				}
			}
		}
		
		[Column(Storage="_VFX_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime VFX_DateCreated
		{
			get
			{
				return this._VFX_DateCreated;
			}
			set
			{
				if ((this._VFX_DateCreated != value))
				{
					this._VFX_DateCreated = value;
				}
			}
		}
		
		[Column(Storage="_VFX_DateUpdated", DbType="DateTime NOT NULL")]
		public System.DateTime VFX_DateUpdated
		{
			get
			{
				return this._VFX_DateUpdated;
			}
			set
			{
				if ((this._VFX_DateUpdated != value))
				{
					this._VFX_DateUpdated = value;
				}
			}
		}
		
		[Column(Storage="_VFX_DateDeleted", DbType="DateTime")]
		public System.Nullable<System.DateTime> VFX_DateDeleted
		{
			get
			{
				return this._VFX_DateDeleted;
			}
			set
			{
				if ((this._VFX_DateDeleted != value))
				{
					this._VFX_DateDeleted = value;
				}
			}
		}
		
		[Column(Storage="_Seller", DbType="BigInt NOT NULL")]
		public long Seller
		{
			get
			{
				return this._Seller;
			}
			set
			{
				if ((this._Seller != value))
				{
					this._Seller = value;
				}
			}
		}
		
		[Column(Storage="_Package", DbType="BigInt NOT NULL")]
		public long Package
		{
			get
			{
				return this._Package;
			}
			set
			{
				if ((this._Package != value))
				{
					this._Package = value;
				}
			}
		}
		
		[Column(Storage="_CommitStatus", DbType="NVarChar(20)")]
		public string CommitStatus
		{
			get
			{
				return this._CommitStatus;
			}
			set
			{
				if ((this._CommitStatus != value))
				{
					this._CommitStatus = value;
				}
			}
		}
		
		[Column(Storage="_Vehicle", DbType="BigInt")]
		public System.Nullable<long> Vehicle
		{
			get
			{
				return this._Vehicle;
			}
			set
			{
				if ((this._Vehicle != value))
				{
					this._Vehicle = value;
				}
			}
		}
		
		[Column(Storage="_Account", DbType="BigInt")]
		public System.Nullable<long> Account
		{
			get
			{
				return this._Account;
			}
			set
			{
				if ((this._Account != value))
				{
					this._Account = value;
				}
			}
		}
		
		[Column(Storage="_TransactionResponse", DbType="BigInt")]
		public System.Nullable<long> TransactionResponse
		{
			get
			{
				return this._TransactionResponse;
			}
			set
			{
				if ((this._TransactionResponse != value))
				{
					this._TransactionResponse = value;
				}
			}
		}
		
		[Column(Storage="_SessionKey", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid SessionKey
		{
			get
			{
				return this._SessionKey;
			}
			set
			{
				if ((this._SessionKey != value))
				{
					this._SessionKey = value;
				}
			}
		}
		
		[Column(Storage="_ETL_NaturalKey", DbType="VarChar(256)")]
		public string ETL_NaturalKey
		{
			get
			{
				return this._ETL_NaturalKey;
			}
			set
			{
				if ((this._ETL_NaturalKey != value))
				{
					this._ETL_NaturalKey = value;
				}
			}
		}
		
		[Column(Storage="_ETL_Hash", DbType="Binary(16)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ETL_Hash
		{
			get
			{
				return this._ETL_Hash;
			}
			set
			{
				if ((this._ETL_Hash != value))
				{
					this._ETL_Hash = value;
				}
			}
		}
		
		[Column(Storage="_ETL_JobCategory", DbType="VarChar(50)")]
		public string ETL_JobCategory
		{
			get
			{
				return this._ETL_JobCategory;
			}
			set
			{
				if ((this._ETL_JobCategory != value))
				{
					this._ETL_JobCategory = value;
				}
			}
		}
		
		[Column(Storage="_ETL_DateEffective", DbType="DateTime")]
		public System.Nullable<System.DateTime> ETL_DateEffective
		{
			get
			{
				return this._ETL_DateEffective;
			}
			set
			{
				if ((this._ETL_DateEffective != value))
				{
					this._ETL_DateEffective = value;
				}
			}
		}
	}
	
	[Table(Name="SellYourCar.PrivateSellerOptionsTable")]
	public partial class PrivateSellerOptionsTable
	{
		
		private long _ID;
		
		private long _VFX_CreatorID;
		
		private long _VFX_UpdaterID;
		
		private System.Nullable<long> _VFX_DeletorID;
		
		private System.DateTime _VFX_DateCreated;
		
		private System.DateTime _VFX_DateUpdated;
		
		private System.Nullable<System.DateTime> _VFX_DateDeleted;
		
		private long _Seller;
		
		private string _OptIn;
		
		private string _ETL_NaturalKey;
		
		private System.Data.Linq.Binary _ETL_Hash;
		
		private string _ETL_JobCategory;
		
		private System.Nullable<System.DateTime> _ETL_DateEffective;
		
		public PrivateSellerOptionsTable()
		{
		}
		
		[Column(Storage="_ID", DbType="BigInt NOT NULL")]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[Column(Storage="_VFX_CreatorID", DbType="BigInt NOT NULL")]
		public long VFX_CreatorID
		{
			get
			{
				return this._VFX_CreatorID;
			}
			set
			{
				if ((this._VFX_CreatorID != value))
				{
					this._VFX_CreatorID = value;
				}
			}
		}
		
		[Column(Storage="_VFX_UpdaterID", DbType="BigInt NOT NULL")]
		public long VFX_UpdaterID
		{
			get
			{
				return this._VFX_UpdaterID;
			}
			set
			{
				if ((this._VFX_UpdaterID != value))
				{
					this._VFX_UpdaterID = value;
				}
			}
		}
		
		[Column(Storage="_VFX_DeletorID", DbType="BigInt")]
		public System.Nullable<long> VFX_DeletorID
		{
			get
			{
				return this._VFX_DeletorID;
			}
			set
			{
				if ((this._VFX_DeletorID != value))
				{
					this._VFX_DeletorID = value;
				}
			}
		}
		
		[Column(Storage="_VFX_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime VFX_DateCreated
		{
			get
			{
				return this._VFX_DateCreated;
			}
			set
			{
				if ((this._VFX_DateCreated != value))
				{
					this._VFX_DateCreated = value;
				}
			}
		}
		
		[Column(Storage="_VFX_DateUpdated", DbType="DateTime NOT NULL")]
		public System.DateTime VFX_DateUpdated
		{
			get
			{
				return this._VFX_DateUpdated;
			}
			set
			{
				if ((this._VFX_DateUpdated != value))
				{
					this._VFX_DateUpdated = value;
				}
			}
		}
		
		[Column(Storage="_VFX_DateDeleted", DbType="DateTime")]
		public System.Nullable<System.DateTime> VFX_DateDeleted
		{
			get
			{
				return this._VFX_DateDeleted;
			}
			set
			{
				if ((this._VFX_DateDeleted != value))
				{
					this._VFX_DateDeleted = value;
				}
			}
		}
		
		[Column(Storage="_Seller", DbType="BigInt NOT NULL")]
		public long Seller
		{
			get
			{
				return this._Seller;
			}
			set
			{
				if ((this._Seller != value))
				{
					this._Seller = value;
				}
			}
		}
		
		[Column(Storage="_OptIn", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string OptIn
		{
			get
			{
				return this._OptIn;
			}
			set
			{
				if ((this._OptIn != value))
				{
					this._OptIn = value;
				}
			}
		}
		
		[Column(Storage="_ETL_NaturalKey", DbType="VarChar(256)")]
		public string ETL_NaturalKey
		{
			get
			{
				return this._ETL_NaturalKey;
			}
			set
			{
				if ((this._ETL_NaturalKey != value))
				{
					this._ETL_NaturalKey = value;
				}
			}
		}
		
		[Column(Storage="_ETL_Hash", DbType="Binary(16)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ETL_Hash
		{
			get
			{
				return this._ETL_Hash;
			}
			set
			{
				if ((this._ETL_Hash != value))
				{
					this._ETL_Hash = value;
				}
			}
		}
		
		[Column(Storage="_ETL_JobCategory", DbType="VarChar(50)")]
		public string ETL_JobCategory
		{
			get
			{
				return this._ETL_JobCategory;
			}
			set
			{
				if ((this._ETL_JobCategory != value))
				{
					this._ETL_JobCategory = value;
				}
			}
		}
		
		[Column(Storage="_ETL_DateEffective", DbType="DateTime")]
		public System.Nullable<System.DateTime> ETL_DateEffective
		{
			get
			{
				return this._ETL_DateEffective;
			}
			set
			{
				if ((this._ETL_DateEffective != value))
				{
					this._ETL_DateEffective = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
