#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nathandelane.WatiN.VehixTesting.Data.VehixFoundation
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="VehixFoundation")]
	public partial class VehixFoundationTasksDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTaskCategoryTable(TaskCategoryTable instance);
    partial void UpdateTaskCategoryTable(TaskCategoryTable instance);
    partial void DeleteTaskCategoryTable(TaskCategoryTable instance);
    partial void InsertTaskTable(TaskTable instance);
    partial void UpdateTaskTable(TaskTable instance);
    partial void DeleteTaskTable(TaskTable instance);
    partial void InsertTaskSecurityRoleTable(TaskSecurityRoleTable instance);
    partial void UpdateTaskSecurityRoleTable(TaskSecurityRoleTable instance);
    partial void DeleteTaskSecurityRoleTable(TaskSecurityRoleTable instance);
    #endregion
		
		public VehixFoundationTasksDataContext() : 
				base(global::Vehix.QA.WebTest.Data.Properties.Settings.Default.VehixFoundationConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public VehixFoundationTasksDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VehixFoundationTasksDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VehixFoundationTasksDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VehixFoundationTasksDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TaskCategoryTable> TaskCategoryTables
		{
			get
			{
				return this.GetTable<TaskCategoryTable>();
			}
		}
		
		public System.Data.Linq.Table<TaskTable> TaskTables
		{
			get
			{
				return this.GetTable<TaskTable>();
			}
		}
		
		public System.Data.Linq.Table<TaskSecurityRoleTable> TaskSecurityRoleTables
		{
			get
			{
				return this.GetTable<TaskSecurityRoleTable>();
			}
		}
		
		public System.Data.Linq.Table<TaskSpaceTable> TaskSpaceTables
		{
			get
			{
				return this.GetTable<TaskSpaceTable>();
			}
		}
	}
	
	[Table(Name="Tasks.TaskCategoryTable")]
	public partial class TaskCategoryTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private System.Nullable<long> _VFX_CreatorID;
		
		private System.Nullable<long> _VFX_UpdaterID;
		
		private System.Nullable<long> _VFX_DeletorID;
		
		private System.DateTime _VFX_DateCreated;
		
		private System.DateTime _VFX_DateUpdated;
		
		private System.Nullable<System.DateTime> _VFX_DateDeleted;
		
		private string _ApplicationName;
		
		private string _Name;
		
		private string _Description;
		
		private string _ETL_NaturalKey;
		
		private System.Data.Linq.Binary _ETL_Hash;
		
		private string _ETL_JobCategory;
		
		private System.Nullable<System.DateTime> _ETL_DateEffective;
		
		private EntitySet<TaskTable> _TaskTables;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnVFX_CreatorIDChanging(System.Nullable<long> value);
    partial void OnVFX_CreatorIDChanged();
    partial void OnVFX_UpdaterIDChanging(System.Nullable<long> value);
    partial void OnVFX_UpdaterIDChanged();
    partial void OnVFX_DeletorIDChanging(System.Nullable<long> value);
    partial void OnVFX_DeletorIDChanged();
    partial void OnVFX_DateCreatedChanging(System.DateTime value);
    partial void OnVFX_DateCreatedChanged();
    partial void OnVFX_DateUpdatedChanging(System.DateTime value);
    partial void OnVFX_DateUpdatedChanged();
    partial void OnVFX_DateDeletedChanging(System.Nullable<System.DateTime> value);
    partial void OnVFX_DateDeletedChanged();
    partial void OnApplicationNameChanging(string value);
    partial void OnApplicationNameChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnETL_NaturalKeyChanging(string value);
    partial void OnETL_NaturalKeyChanged();
    partial void OnETL_HashChanging(System.Data.Linq.Binary value);
    partial void OnETL_HashChanged();
    partial void OnETL_JobCategoryChanging(string value);
    partial void OnETL_JobCategoryChanged();
    partial void OnETL_DateEffectiveChanging(System.Nullable<System.DateTime> value);
    partial void OnETL_DateEffectiveChanged();
    #endregion
		
		public TaskCategoryTable()
		{
			this._TaskTables = new EntitySet<TaskTable>(new Action<TaskTable>(this.attach_TaskTables), new Action<TaskTable>(this.detach_TaskTables));
			OnCreated();
		}
		
		[Column(Storage="_ID", DbType="BigInt NOT NULL")]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_VFX_CreatorID", DbType="BigInt")]
		public System.Nullable<long> VFX_CreatorID
		{
			get
			{
				return this._VFX_CreatorID;
			}
			set
			{
				if ((this._VFX_CreatorID != value))
				{
					this.OnVFX_CreatorIDChanging(value);
					this.SendPropertyChanging();
					this._VFX_CreatorID = value;
					this.SendPropertyChanged("VFX_CreatorID");
					this.OnVFX_CreatorIDChanged();
				}
			}
		}
		
		[Column(Storage="_VFX_UpdaterID", DbType="BigInt")]
		public System.Nullable<long> VFX_UpdaterID
		{
			get
			{
				return this._VFX_UpdaterID;
			}
			set
			{
				if ((this._VFX_UpdaterID != value))
				{
					this.OnVFX_UpdaterIDChanging(value);
					this.SendPropertyChanging();
					this._VFX_UpdaterID = value;
					this.SendPropertyChanged("VFX_UpdaterID");
					this.OnVFX_UpdaterIDChanged();
				}
			}
		}
		
		[Column(Storage="_VFX_DeletorID", DbType="BigInt")]
		public System.Nullable<long> VFX_DeletorID
		{
			get
			{
				return this._VFX_DeletorID;
			}
			set
			{
				if ((this._VFX_DeletorID != value))
				{
					this.OnVFX_DeletorIDChanging(value);
					this.SendPropertyChanging();
					this._VFX_DeletorID = value;
					this.SendPropertyChanged("VFX_DeletorID");
					this.OnVFX_DeletorIDChanged();
				}
			}
		}
		
		[Column(Storage="_VFX_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime VFX_DateCreated
		{
			get
			{
				return this._VFX_DateCreated;
			}
			set
			{
				if ((this._VFX_DateCreated != value))
				{
					this.OnVFX_DateCreatedChanging(value);
					this.SendPropertyChanging();
					this._VFX_DateCreated = value;
					this.SendPropertyChanged("VFX_DateCreated");
					this.OnVFX_DateCreatedChanged();
				}
			}
		}
		
		[Column(Storage="_VFX_DateUpdated", DbType="DateTime NOT NULL")]
		public System.DateTime VFX_DateUpdated
		{
			get
			{
				return this._VFX_DateUpdated;
			}
			set
			{
				if ((this._VFX_DateUpdated != value))
				{
					this.OnVFX_DateUpdatedChanging(value);
					this.SendPropertyChanging();
					this._VFX_DateUpdated = value;
					this.SendPropertyChanged("VFX_DateUpdated");
					this.OnVFX_DateUpdatedChanged();
				}
			}
		}
		
		[Column(Storage="_VFX_DateDeleted", DbType="DateTime")]
		public System.Nullable<System.DateTime> VFX_DateDeleted
		{
			get
			{
				return this._VFX_DateDeleted;
			}
			set
			{
				if ((this._VFX_DateDeleted != value))
				{
					this.OnVFX_DateDeletedChanging(value);
					this.SendPropertyChanging();
					this._VFX_DateDeleted = value;
					this.SendPropertyChanged("VFX_DateDeleted");
					this.OnVFX_DateDeletedChanged();
				}
			}
		}
		
		[Column(Storage="_ApplicationName", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ApplicationName
		{
			get
			{
				return this._ApplicationName;
			}
			set
			{
				if ((this._ApplicationName != value))
				{
					this.OnApplicationNameChanging(value);
					this.SendPropertyChanging();
					this._ApplicationName = value;
					this.SendPropertyChanged("ApplicationName");
					this.OnApplicationNameChanged();
				}
			}
		}
		
		[Column(Storage="_Name", DbType="NVarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[Column(Storage="_Description", DbType="NVarChar(400)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[Column(Storage="_ETL_NaturalKey", DbType="VarChar(256)")]
		public string ETL_NaturalKey
		{
			get
			{
				return this._ETL_NaturalKey;
			}
			set
			{
				if ((this._ETL_NaturalKey != value))
				{
					this.OnETL_NaturalKeyChanging(value);
					this.SendPropertyChanging();
					this._ETL_NaturalKey = value;
					this.SendPropertyChanged("ETL_NaturalKey");
					this.OnETL_NaturalKeyChanged();
				}
			}
		}
		
		[Column(Storage="_ETL_Hash", DbType="Binary(16)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ETL_Hash
		{
			get
			{
				return this._ETL_Hash;
			}
			set
			{
				if ((this._ETL_Hash != value))
				{
					this.OnETL_HashChanging(value);
					this.SendPropertyChanging();
					this._ETL_Hash = value;
					this.SendPropertyChanged("ETL_Hash");
					this.OnETL_HashChanged();
				}
			}
		}
		
		[Column(Storage="_ETL_JobCategory", DbType="VarChar(50)")]
		public string ETL_JobCategory
		{
			get
			{
				return this._ETL_JobCategory;
			}
			set
			{
				if ((this._ETL_JobCategory != value))
				{
					this.OnETL_JobCategoryChanging(value);
					this.SendPropertyChanging();
					this._ETL_JobCategory = value;
					this.SendPropertyChanged("ETL_JobCategory");
					this.OnETL_JobCategoryChanged();
				}
			}
		}
		
		[Column(Storage="_ETL_DateEffective", DbType="DateTime")]
		public System.Nullable<System.DateTime> ETL_DateEffective
		{
			get
			{
				return this._ETL_DateEffective;
			}
			set
			{
				if ((this._ETL_DateEffective != value))
				{
					this.OnETL_DateEffectiveChanging(value);
					this.SendPropertyChanging();
					this._ETL_DateEffective = value;
					this.SendPropertyChanged("ETL_DateEffective");
					this.OnETL_DateEffectiveChanged();
				}
			}
		}
		
		[Association(Name="TaskCategoryTable_TaskTable", Storage="_TaskTables", ThisKey="ID", OtherKey="Category")]
		public EntitySet<TaskTable> TaskTables
		{
			get
			{
				return this._TaskTables;
			}
			set
			{
				this._TaskTables.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TaskTables(TaskTable entity)
		{
			this.SendPropertyChanging();
			entity.TaskCategoryTable = this;
		}
		
		private void detach_TaskTables(TaskTable entity)
		{
			this.SendPropertyChanging();
			entity.TaskCategoryTable = null;
		}
	}
	
	[Table(Name="Tasks.TaskTable")]
	public partial class TaskTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private System.Nullable<long> _VFX_CreatorID;
		
		private System.Nullable<long> _VFX_UpdaterID;
		
		private System.Nullable<long> _VFX_DeletorID;
		
		private System.DateTime _VFX_DateCreated;
		
		private System.DateTime _VFX_DateUpdated;
		
		private System.Nullable<System.DateTime> _VFX_DateDeleted;
		
		private string _ApplicationName;
		
		private string _Name;
		
		private long _Category;
		
		private string _Description;
		
		private string _PageURL;
		
		private int _Priority;
		
		private string _ETL_NaturalKey;
		
		private System.Data.Linq.Binary _ETL_Hash;
		
		private string _ETL_JobCategory;
		
		private System.Nullable<System.DateTime> _ETL_DateEffective;
		
		private EntitySet<TaskSecurityRoleTable> _TaskSecurityRoleTables;
		
		private EntityRef<TaskCategoryTable> _TaskCategoryTable;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnVFX_CreatorIDChanging(System.Nullable<long> value);
    partial void OnVFX_CreatorIDChanged();
    partial void OnVFX_UpdaterIDChanging(System.Nullable<long> value);
    partial void OnVFX_UpdaterIDChanged();
    partial void OnVFX_DeletorIDChanging(System.Nullable<long> value);
    partial void OnVFX_DeletorIDChanged();
    partial void OnVFX_DateCreatedChanging(System.DateTime value);
    partial void OnVFX_DateCreatedChanged();
    partial void OnVFX_DateUpdatedChanging(System.DateTime value);
    partial void OnVFX_DateUpdatedChanged();
    partial void OnVFX_DateDeletedChanging(System.Nullable<System.DateTime> value);
    partial void OnVFX_DateDeletedChanged();
    partial void OnApplicationNameChanging(string value);
    partial void OnApplicationNameChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnCategoryChanging(long value);
    partial void OnCategoryChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnPageURLChanging(string value);
    partial void OnPageURLChanged();
    partial void OnPriorityChanging(int value);
    partial void OnPriorityChanged();
    partial void OnETL_NaturalKeyChanging(string value);
    partial void OnETL_NaturalKeyChanged();
    partial void OnETL_HashChanging(System.Data.Linq.Binary value);
    partial void OnETL_HashChanged();
    partial void OnETL_JobCategoryChanging(string value);
    partial void OnETL_JobCategoryChanged();
    partial void OnETL_DateEffectiveChanging(System.Nullable<System.DateTime> value);
    partial void OnETL_DateEffectiveChanged();
    #endregion
		
		public TaskTable()
		{
			this._TaskSecurityRoleTables = new EntitySet<TaskSecurityRoleTable>(new Action<TaskSecurityRoleTable>(this.attach_TaskSecurityRoleTables), new Action<TaskSecurityRoleTable>(this.detach_TaskSecurityRoleTables));
			this._TaskCategoryTable = default(EntityRef<TaskCategoryTable>);
			OnCreated();
		}
		
		[Column(Storage="_ID", DbType="BigInt NOT NULL")]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_VFX_CreatorID", DbType="BigInt")]
		public System.Nullable<long> VFX_CreatorID
		{
			get
			{
				return this._VFX_CreatorID;
			}
			set
			{
				if ((this._VFX_CreatorID != value))
				{
					this.OnVFX_CreatorIDChanging(value);
					this.SendPropertyChanging();
					this._VFX_CreatorID = value;
					this.SendPropertyChanged("VFX_CreatorID");
					this.OnVFX_CreatorIDChanged();
				}
			}
		}
		
		[Column(Storage="_VFX_UpdaterID", DbType="BigInt")]
		public System.Nullable<long> VFX_UpdaterID
		{
			get
			{
				return this._VFX_UpdaterID;
			}
			set
			{
				if ((this._VFX_UpdaterID != value))
				{
					this.OnVFX_UpdaterIDChanging(value);
					this.SendPropertyChanging();
					this._VFX_UpdaterID = value;
					this.SendPropertyChanged("VFX_UpdaterID");
					this.OnVFX_UpdaterIDChanged();
				}
			}
		}
		
		[Column(Storage="_VFX_DeletorID", DbType="BigInt")]
		public System.Nullable<long> VFX_DeletorID
		{
			get
			{
				return this._VFX_DeletorID;
			}
			set
			{
				if ((this._VFX_DeletorID != value))
				{
					this.OnVFX_DeletorIDChanging(value);
					this.SendPropertyChanging();
					this._VFX_DeletorID = value;
					this.SendPropertyChanged("VFX_DeletorID");
					this.OnVFX_DeletorIDChanged();
				}
			}
		}
		
		[Column(Storage="_VFX_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime VFX_DateCreated
		{
			get
			{
				return this._VFX_DateCreated;
			}
			set
			{
				if ((this._VFX_DateCreated != value))
				{
					this.OnVFX_DateCreatedChanging(value);
					this.SendPropertyChanging();
					this._VFX_DateCreated = value;
					this.SendPropertyChanged("VFX_DateCreated");
					this.OnVFX_DateCreatedChanged();
				}
			}
		}
		
		[Column(Storage="_VFX_DateUpdated", DbType="DateTime NOT NULL")]
		public System.DateTime VFX_DateUpdated
		{
			get
			{
				return this._VFX_DateUpdated;
			}
			set
			{
				if ((this._VFX_DateUpdated != value))
				{
					this.OnVFX_DateUpdatedChanging(value);
					this.SendPropertyChanging();
					this._VFX_DateUpdated = value;
					this.SendPropertyChanged("VFX_DateUpdated");
					this.OnVFX_DateUpdatedChanged();
				}
			}
		}
		
		[Column(Storage="_VFX_DateDeleted", DbType="DateTime")]
		public System.Nullable<System.DateTime> VFX_DateDeleted
		{
			get
			{
				return this._VFX_DateDeleted;
			}
			set
			{
				if ((this._VFX_DateDeleted != value))
				{
					this.OnVFX_DateDeletedChanging(value);
					this.SendPropertyChanging();
					this._VFX_DateDeleted = value;
					this.SendPropertyChanged("VFX_DateDeleted");
					this.OnVFX_DateDeletedChanged();
				}
			}
		}
		
		[Column(Storage="_ApplicationName", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ApplicationName
		{
			get
			{
				return this._ApplicationName;
			}
			set
			{
				if ((this._ApplicationName != value))
				{
					this.OnApplicationNameChanging(value);
					this.SendPropertyChanging();
					this._ApplicationName = value;
					this.SendPropertyChanged("ApplicationName");
					this.OnApplicationNameChanged();
				}
			}
		}
		
		[Column(Storage="_Name", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[Column(Storage="_Category", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					if (this._TaskCategoryTable.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCategoryChanging(value);
					this.SendPropertyChanging();
					this._Category = value;
					this.SendPropertyChanged("Category");
					this.OnCategoryChanged();
				}
			}
		}
		
		[Column(Storage="_Description", DbType="NVarChar(400)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[Column(Storage="_PageURL", DbType="NVarChar(400) NOT NULL", CanBeNull=false)]
		public string PageURL
		{
			get
			{
				return this._PageURL;
			}
			set
			{
				if ((this._PageURL != value))
				{
					this.OnPageURLChanging(value);
					this.SendPropertyChanging();
					this._PageURL = value;
					this.SendPropertyChanged("PageURL");
					this.OnPageURLChanged();
				}
			}
		}
		
		[Column(Storage="_Priority", DbType="Int NOT NULL")]
		public int Priority
		{
			get
			{
				return this._Priority;
			}
			set
			{
				if ((this._Priority != value))
				{
					this.OnPriorityChanging(value);
					this.SendPropertyChanging();
					this._Priority = value;
					this.SendPropertyChanged("Priority");
					this.OnPriorityChanged();
				}
			}
		}
		
		[Column(Storage="_ETL_NaturalKey", DbType="VarChar(256)")]
		public string ETL_NaturalKey
		{
			get
			{
				return this._ETL_NaturalKey;
			}
			set
			{
				if ((this._ETL_NaturalKey != value))
				{
					this.OnETL_NaturalKeyChanging(value);
					this.SendPropertyChanging();
					this._ETL_NaturalKey = value;
					this.SendPropertyChanged("ETL_NaturalKey");
					this.OnETL_NaturalKeyChanged();
				}
			}
		}
		
		[Column(Storage="_ETL_Hash", DbType="Binary(16)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ETL_Hash
		{
			get
			{
				return this._ETL_Hash;
			}
			set
			{
				if ((this._ETL_Hash != value))
				{
					this.OnETL_HashChanging(value);
					this.SendPropertyChanging();
					this._ETL_Hash = value;
					this.SendPropertyChanged("ETL_Hash");
					this.OnETL_HashChanged();
				}
			}
		}
		
		[Column(Storage="_ETL_JobCategory", DbType="VarChar(50)")]
		public string ETL_JobCategory
		{
			get
			{
				return this._ETL_JobCategory;
			}
			set
			{
				if ((this._ETL_JobCategory != value))
				{
					this.OnETL_JobCategoryChanging(value);
					this.SendPropertyChanging();
					this._ETL_JobCategory = value;
					this.SendPropertyChanged("ETL_JobCategory");
					this.OnETL_JobCategoryChanged();
				}
			}
		}
		
		[Column(Storage="_ETL_DateEffective", DbType="DateTime")]
		public System.Nullable<System.DateTime> ETL_DateEffective
		{
			get
			{
				return this._ETL_DateEffective;
			}
			set
			{
				if ((this._ETL_DateEffective != value))
				{
					this.OnETL_DateEffectiveChanging(value);
					this.SendPropertyChanging();
					this._ETL_DateEffective = value;
					this.SendPropertyChanged("ETL_DateEffective");
					this.OnETL_DateEffectiveChanged();
				}
			}
		}
		
		[Association(Name="TaskTable_TaskSecurityRoleTable", Storage="_TaskSecurityRoleTables", ThisKey="ID", OtherKey="Task")]
		public EntitySet<TaskSecurityRoleTable> TaskSecurityRoleTables
		{
			get
			{
				return this._TaskSecurityRoleTables;
			}
			set
			{
				this._TaskSecurityRoleTables.Assign(value);
			}
		}
		
		[Association(Name="TaskCategoryTable_TaskTable", Storage="_TaskCategoryTable", ThisKey="Category", OtherKey="ID", IsForeignKey=true)]
		public TaskCategoryTable TaskCategoryTable
		{
			get
			{
				return this._TaskCategoryTable.Entity;
			}
			set
			{
				TaskCategoryTable previousValue = this._TaskCategoryTable.Entity;
				if (((previousValue != value) 
							|| (this._TaskCategoryTable.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaskCategoryTable.Entity = null;
						previousValue.TaskTables.Remove(this);
					}
					this._TaskCategoryTable.Entity = value;
					if ((value != null))
					{
						value.TaskTables.Add(this);
						this._Category = value.ID;
					}
					else
					{
						this._Category = default(long);
					}
					this.SendPropertyChanged("TaskCategoryTable");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TaskSecurityRoleTables(TaskSecurityRoleTable entity)
		{
			this.SendPropertyChanging();
			entity.TaskTable = this;
		}
		
		private void detach_TaskSecurityRoleTables(TaskSecurityRoleTable entity)
		{
			this.SendPropertyChanging();
			entity.TaskTable = null;
		}
	}
	
	[Table(Name="Tasks.TaskSecurityRoleTable")]
	public partial class TaskSecurityRoleTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private System.Nullable<long> _VFX_CreatorID;
		
		private System.Nullable<long> _VFX_UpdaterID;
		
		private System.Nullable<long> _VFX_DeletorID;
		
		private System.DateTime _VFX_DateCreated;
		
		private System.DateTime _VFX_DateUpdated;
		
		private System.Nullable<System.DateTime> _VFX_DateDeleted;
		
		private long _Role;
		
		private string _ApplicationName;
		
		private string _RoleName;
		
		private long _Task;
		
		private int _Priority;
		
		private string _ETL_NaturalKey;
		
		private System.Data.Linq.Binary _ETL_Hash;
		
		private string _ETL_JobCategory;
		
		private System.Nullable<System.DateTime> _ETL_DateEffective;
		
		private EntityRef<TaskTable> _TaskTable;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnVFX_CreatorIDChanging(System.Nullable<long> value);
    partial void OnVFX_CreatorIDChanged();
    partial void OnVFX_UpdaterIDChanging(System.Nullable<long> value);
    partial void OnVFX_UpdaterIDChanged();
    partial void OnVFX_DeletorIDChanging(System.Nullable<long> value);
    partial void OnVFX_DeletorIDChanged();
    partial void OnVFX_DateCreatedChanging(System.DateTime value);
    partial void OnVFX_DateCreatedChanged();
    partial void OnVFX_DateUpdatedChanging(System.DateTime value);
    partial void OnVFX_DateUpdatedChanged();
    partial void OnVFX_DateDeletedChanging(System.Nullable<System.DateTime> value);
    partial void OnVFX_DateDeletedChanged();
    partial void OnRoleChanging(long value);
    partial void OnRoleChanged();
    partial void OnApplicationNameChanging(string value);
    partial void OnApplicationNameChanged();
    partial void OnRoleNameChanging(string value);
    partial void OnRoleNameChanged();
    partial void OnTaskChanging(long value);
    partial void OnTaskChanged();
    partial void OnPriorityChanging(int value);
    partial void OnPriorityChanged();
    partial void OnETL_NaturalKeyChanging(string value);
    partial void OnETL_NaturalKeyChanged();
    partial void OnETL_HashChanging(System.Data.Linq.Binary value);
    partial void OnETL_HashChanged();
    partial void OnETL_JobCategoryChanging(string value);
    partial void OnETL_JobCategoryChanged();
    partial void OnETL_DateEffectiveChanging(System.Nullable<System.DateTime> value);
    partial void OnETL_DateEffectiveChanged();
    #endregion
		
		public TaskSecurityRoleTable()
		{
			this._TaskTable = default(EntityRef<TaskTable>);
			OnCreated();
		}
		
		[Column(Storage="_ID", DbType="BigInt NOT NULL")]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_VFX_CreatorID", DbType="BigInt")]
		public System.Nullable<long> VFX_CreatorID
		{
			get
			{
				return this._VFX_CreatorID;
			}
			set
			{
				if ((this._VFX_CreatorID != value))
				{
					this.OnVFX_CreatorIDChanging(value);
					this.SendPropertyChanging();
					this._VFX_CreatorID = value;
					this.SendPropertyChanged("VFX_CreatorID");
					this.OnVFX_CreatorIDChanged();
				}
			}
		}
		
		[Column(Storage="_VFX_UpdaterID", DbType="BigInt")]
		public System.Nullable<long> VFX_UpdaterID
		{
			get
			{
				return this._VFX_UpdaterID;
			}
			set
			{
				if ((this._VFX_UpdaterID != value))
				{
					this.OnVFX_UpdaterIDChanging(value);
					this.SendPropertyChanging();
					this._VFX_UpdaterID = value;
					this.SendPropertyChanged("VFX_UpdaterID");
					this.OnVFX_UpdaterIDChanged();
				}
			}
		}
		
		[Column(Storage="_VFX_DeletorID", DbType="BigInt")]
		public System.Nullable<long> VFX_DeletorID
		{
			get
			{
				return this._VFX_DeletorID;
			}
			set
			{
				if ((this._VFX_DeletorID != value))
				{
					this.OnVFX_DeletorIDChanging(value);
					this.SendPropertyChanging();
					this._VFX_DeletorID = value;
					this.SendPropertyChanged("VFX_DeletorID");
					this.OnVFX_DeletorIDChanged();
				}
			}
		}
		
		[Column(Storage="_VFX_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime VFX_DateCreated
		{
			get
			{
				return this._VFX_DateCreated;
			}
			set
			{
				if ((this._VFX_DateCreated != value))
				{
					this.OnVFX_DateCreatedChanging(value);
					this.SendPropertyChanging();
					this._VFX_DateCreated = value;
					this.SendPropertyChanged("VFX_DateCreated");
					this.OnVFX_DateCreatedChanged();
				}
			}
		}
		
		[Column(Storage="_VFX_DateUpdated", DbType="DateTime NOT NULL")]
		public System.DateTime VFX_DateUpdated
		{
			get
			{
				return this._VFX_DateUpdated;
			}
			set
			{
				if ((this._VFX_DateUpdated != value))
				{
					this.OnVFX_DateUpdatedChanging(value);
					this.SendPropertyChanging();
					this._VFX_DateUpdated = value;
					this.SendPropertyChanged("VFX_DateUpdated");
					this.OnVFX_DateUpdatedChanged();
				}
			}
		}
		
		[Column(Storage="_VFX_DateDeleted", DbType="DateTime")]
		public System.Nullable<System.DateTime> VFX_DateDeleted
		{
			get
			{
				return this._VFX_DateDeleted;
			}
			set
			{
				if ((this._VFX_DateDeleted != value))
				{
					this.OnVFX_DateDeletedChanging(value);
					this.SendPropertyChanging();
					this._VFX_DateDeleted = value;
					this.SendPropertyChanged("VFX_DateDeleted");
					this.OnVFX_DateDeletedChanged();
				}
			}
		}
		
		[Column(Storage="_Role", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this.OnRoleChanging(value);
					this.SendPropertyChanging();
					this._Role = value;
					this.SendPropertyChanged("Role");
					this.OnRoleChanged();
				}
			}
		}
		
		[Column(Storage="_ApplicationName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ApplicationName
		{
			get
			{
				return this._ApplicationName;
			}
			set
			{
				if ((this._ApplicationName != value))
				{
					this.OnApplicationNameChanging(value);
					this.SendPropertyChanging();
					this._ApplicationName = value;
					this.SendPropertyChanged("ApplicationName");
					this.OnApplicationNameChanged();
				}
			}
		}
		
		[Column(Storage="_RoleName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string RoleName
		{
			get
			{
				return this._RoleName;
			}
			set
			{
				if ((this._RoleName != value))
				{
					this.OnRoleNameChanging(value);
					this.SendPropertyChanging();
					this._RoleName = value;
					this.SendPropertyChanged("RoleName");
					this.OnRoleNameChanged();
				}
			}
		}
		
		[Column(Storage="_Task", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Task
		{
			get
			{
				return this._Task;
			}
			set
			{
				if ((this._Task != value))
				{
					if (this._TaskTable.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTaskChanging(value);
					this.SendPropertyChanging();
					this._Task = value;
					this.SendPropertyChanged("Task");
					this.OnTaskChanged();
				}
			}
		}
		
		[Column(Storage="_Priority", DbType="Int NOT NULL")]
		public int Priority
		{
			get
			{
				return this._Priority;
			}
			set
			{
				if ((this._Priority != value))
				{
					this.OnPriorityChanging(value);
					this.SendPropertyChanging();
					this._Priority = value;
					this.SendPropertyChanged("Priority");
					this.OnPriorityChanged();
				}
			}
		}
		
		[Column(Storage="_ETL_NaturalKey", DbType="VarChar(256)")]
		public string ETL_NaturalKey
		{
			get
			{
				return this._ETL_NaturalKey;
			}
			set
			{
				if ((this._ETL_NaturalKey != value))
				{
					this.OnETL_NaturalKeyChanging(value);
					this.SendPropertyChanging();
					this._ETL_NaturalKey = value;
					this.SendPropertyChanged("ETL_NaturalKey");
					this.OnETL_NaturalKeyChanged();
				}
			}
		}
		
		[Column(Storage="_ETL_Hash", DbType="Binary(16)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ETL_Hash
		{
			get
			{
				return this._ETL_Hash;
			}
			set
			{
				if ((this._ETL_Hash != value))
				{
					this.OnETL_HashChanging(value);
					this.SendPropertyChanging();
					this._ETL_Hash = value;
					this.SendPropertyChanged("ETL_Hash");
					this.OnETL_HashChanged();
				}
			}
		}
		
		[Column(Storage="_ETL_JobCategory", DbType="VarChar(50)")]
		public string ETL_JobCategory
		{
			get
			{
				return this._ETL_JobCategory;
			}
			set
			{
				if ((this._ETL_JobCategory != value))
				{
					this.OnETL_JobCategoryChanging(value);
					this.SendPropertyChanging();
					this._ETL_JobCategory = value;
					this.SendPropertyChanged("ETL_JobCategory");
					this.OnETL_JobCategoryChanged();
				}
			}
		}
		
		[Column(Storage="_ETL_DateEffective", DbType="DateTime")]
		public System.Nullable<System.DateTime> ETL_DateEffective
		{
			get
			{
				return this._ETL_DateEffective;
			}
			set
			{
				if ((this._ETL_DateEffective != value))
				{
					this.OnETL_DateEffectiveChanging(value);
					this.SendPropertyChanging();
					this._ETL_DateEffective = value;
					this.SendPropertyChanged("ETL_DateEffective");
					this.OnETL_DateEffectiveChanged();
				}
			}
		}
		
		[Association(Name="TaskTable_TaskSecurityRoleTable", Storage="_TaskTable", ThisKey="Task", OtherKey="ID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public TaskTable TaskTable
		{
			get
			{
				return this._TaskTable.Entity;
			}
			set
			{
				TaskTable previousValue = this._TaskTable.Entity;
				if (((previousValue != value) 
							|| (this._TaskTable.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaskTable.Entity = null;
						previousValue.TaskSecurityRoleTables.Remove(this);
					}
					this._TaskTable.Entity = value;
					if ((value != null))
					{
						value.TaskSecurityRoleTables.Add(this);
						this._Task = value.ID;
					}
					else
					{
						this._Task = default(long);
					}
					this.SendPropertyChanged("TaskTable");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="Tasks.TaskSpaceTable")]
	public partial class TaskSpaceTable
	{
		
		private long _ID;
		
		private string _Isolated;
		
		private string _ETL_NaturalKey;
		
		private System.Data.Linq.Binary _ETL_Hash;
		
		private string _ETL_JobCategory;
		
		private System.Nullable<System.DateTime> _ETL_DateEffective;
		
		public TaskSpaceTable()
		{
		}
		
		[Column(Storage="_ID", DbType="BigInt NOT NULL")]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[Column(Storage="_Isolated", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string Isolated
		{
			get
			{
				return this._Isolated;
			}
			set
			{
				if ((this._Isolated != value))
				{
					this._Isolated = value;
				}
			}
		}
		
		[Column(Storage="_ETL_NaturalKey", DbType="VarChar(256)")]
		public string ETL_NaturalKey
		{
			get
			{
				return this._ETL_NaturalKey;
			}
			set
			{
				if ((this._ETL_NaturalKey != value))
				{
					this._ETL_NaturalKey = value;
				}
			}
		}
		
		[Column(Storage="_ETL_Hash", DbType="Binary(16)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ETL_Hash
		{
			get
			{
				return this._ETL_Hash;
			}
			set
			{
				if ((this._ETL_Hash != value))
				{
					this._ETL_Hash = value;
				}
			}
		}
		
		[Column(Storage="_ETL_JobCategory", DbType="VarChar(50)")]
		public string ETL_JobCategory
		{
			get
			{
				return this._ETL_JobCategory;
			}
			set
			{
				if ((this._ETL_JobCategory != value))
				{
					this._ETL_JobCategory = value;
				}
			}
		}
		
		[Column(Storage="_ETL_DateEffective", DbType="DateTime")]
		public System.Nullable<System.DateTime> ETL_DateEffective
		{
			get
			{
				return this._ETL_DateEffective;
			}
			set
			{
				if ((this._ETL_DateEffective != value))
				{
					this._ETL_DateEffective = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
